// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Breadcrumb.proto

package co.viewfinder.proto;

public final class BreadcrumbPB {
  private BreadcrumbPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BreadcrumbOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Location location = 1;
    /**
     * <code>optional .Location location = 1;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .Location location = 1;</code>
     */
    co.viewfinder.proto.LocationPB.Location getLocation();
    /**
     * <code>optional .Location location = 1;</code>
     */
    co.viewfinder.proto.LocationPB.LocationOrBuilder getLocationOrBuilder();

    // optional .Placemark placemark = 2;
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    boolean hasPlacemark();
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    co.viewfinder.proto.PlacemarkPB.Placemark getPlacemark();
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getPlacemarkOrBuilder();

    // optional double timestamp = 3;
    /**
     * <code>optional double timestamp = 3;</code>
     *
     * <pre>
     * The time when the breadcrumb was gathered.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional double timestamp = 3;</code>
     *
     * <pre>
     * The time when the breadcrumb was gathered.
     * </pre>
     */
    double getTimestamp();

    // optional string debug = 4;
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    boolean hasDebug();
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    java.lang.String getDebug();
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    com.google.protobuf.ByteString
        getDebugBytes();
  }
  /**
   * Protobuf type {@code Breadcrumb}
   */
  public static final class Breadcrumb extends
      com.google.protobuf.GeneratedMessage
      implements BreadcrumbOrBuilder {
    // Use Breadcrumb.newBuilder() to construct.
    private Breadcrumb(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Breadcrumb(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Breadcrumb defaultInstance;
    public static Breadcrumb getDefaultInstance() {
      return defaultInstance;
    }

    public Breadcrumb getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Breadcrumb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              co.viewfinder.proto.LocationPB.Location.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(co.viewfinder.proto.LocationPB.Location.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              co.viewfinder.proto.PlacemarkPB.Placemark.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = placemark_.toBuilder();
              }
              placemark_ = input.readMessage(co.viewfinder.proto.PlacemarkPB.Placemark.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(placemark_);
                placemark_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readDouble();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              debug_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.BreadcrumbPB.internal_static_Breadcrumb_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.BreadcrumbPB.internal_static_Breadcrumb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.BreadcrumbPB.Breadcrumb.class, co.viewfinder.proto.BreadcrumbPB.Breadcrumb.Builder.class);
    }

    public static com.google.protobuf.Parser<Breadcrumb> PARSER =
        new com.google.protobuf.AbstractParser<Breadcrumb>() {
      public Breadcrumb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Breadcrumb(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Breadcrumb> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .Location location = 1;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private co.viewfinder.proto.LocationPB.Location location_;
    /**
     * <code>optional .Location location = 1;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    public co.viewfinder.proto.LocationPB.Location getLocation() {
      return location_;
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    public co.viewfinder.proto.LocationPB.LocationOrBuilder getLocationOrBuilder() {
      return location_;
    }

    // optional .Placemark placemark = 2;
    public static final int PLACEMARK_FIELD_NUMBER = 2;
    private co.viewfinder.proto.PlacemarkPB.Placemark placemark_;
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    public boolean hasPlacemark() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    public co.viewfinder.proto.PlacemarkPB.Placemark getPlacemark() {
      return placemark_;
    }
    /**
     * <code>optional .Placemark placemark = 2;</code>
     */
    public co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getPlacemarkOrBuilder() {
      return placemark_;
    }

    // optional double timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private double timestamp_;
    /**
     * <code>optional double timestamp = 3;</code>
     *
     * <pre>
     * The time when the breadcrumb was gathered.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double timestamp = 3;</code>
     *
     * <pre>
     * The time when the breadcrumb was gathered.
     * </pre>
     */
    public double getTimestamp() {
      return timestamp_;
    }

    // optional string debug = 4;
    public static final int DEBUG_FIELD_NUMBER = 4;
    private java.lang.Object debug_;
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    public boolean hasDebug() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    public java.lang.String getDebug() {
      java.lang.Object ref = debug_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          debug_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string debug = 4;</code>
     *
     * <pre>
     * Additional non-programmatic data about the breadcrumb (e.g. app state when
     * the breadcrumb was gathered).
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDebugBytes() {
      java.lang.Object ref = debug_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debug_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      location_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
      placemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
      timestamp_ = 0D;
      debug_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, location_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, placemark_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDebugBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, location_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, placemark_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDebugBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.BreadcrumbPB.Breadcrumb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.BreadcrumbPB.Breadcrumb prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Breadcrumb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.BreadcrumbPB.BreadcrumbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.BreadcrumbPB.internal_static_Breadcrumb_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.BreadcrumbPB.internal_static_Breadcrumb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.BreadcrumbPB.Breadcrumb.class, co.viewfinder.proto.BreadcrumbPB.Breadcrumb.Builder.class);
      }

      // Construct using co.viewfinder.proto.BreadcrumbPB.Breadcrumb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
          getPlacemarkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (locationBuilder_ == null) {
          location_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (placemarkBuilder_ == null) {
          placemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
        } else {
          placemarkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        debug_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.BreadcrumbPB.internal_static_Breadcrumb_descriptor;
      }

      public co.viewfinder.proto.BreadcrumbPB.Breadcrumb getDefaultInstanceForType() {
        return co.viewfinder.proto.BreadcrumbPB.Breadcrumb.getDefaultInstance();
      }

      public co.viewfinder.proto.BreadcrumbPB.Breadcrumb build() {
        co.viewfinder.proto.BreadcrumbPB.Breadcrumb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.BreadcrumbPB.Breadcrumb buildPartial() {
        co.viewfinder.proto.BreadcrumbPB.Breadcrumb result = new co.viewfinder.proto.BreadcrumbPB.Breadcrumb(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (placemarkBuilder_ == null) {
          result.placemark_ = placemark_;
        } else {
          result.placemark_ = placemarkBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.debug_ = debug_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.BreadcrumbPB.Breadcrumb) {
          return mergeFrom((co.viewfinder.proto.BreadcrumbPB.Breadcrumb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.BreadcrumbPB.Breadcrumb other) {
        if (other == co.viewfinder.proto.BreadcrumbPB.Breadcrumb.getDefaultInstance()) return this;
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.hasPlacemark()) {
          mergePlacemark(other.getPlacemark());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasDebug()) {
          bitField0_ |= 0x00000008;
          debug_ = other.debug_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.BreadcrumbPB.Breadcrumb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.BreadcrumbPB.Breadcrumb) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Location location = 1;
      private co.viewfinder.proto.LocationPB.Location location_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder> locationBuilder_;
      /**
       * <code>optional .Location location = 1;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public co.viewfinder.proto.LocationPB.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder setLocation(co.viewfinder.proto.LocationPB.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder setLocation(
          co.viewfinder.proto.LocationPB.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder mergeLocation(co.viewfinder.proto.LocationPB.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              location_ != co.viewfinder.proto.LocationPB.Location.getDefaultInstance()) {
            location_ =
              co.viewfinder.proto.LocationPB.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public co.viewfinder.proto.LocationPB.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public co.viewfinder.proto.LocationPB.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_;
        }
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder>(
                  location_,
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // optional .Placemark placemark = 2;
      private co.viewfinder.proto.PlacemarkPB.Placemark placemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder> placemarkBuilder_;
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public boolean hasPlacemark() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.Placemark getPlacemark() {
        if (placemarkBuilder_ == null) {
          return placemark_;
        } else {
          return placemarkBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public Builder setPlacemark(co.viewfinder.proto.PlacemarkPB.Placemark value) {
        if (placemarkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          placemark_ = value;
          onChanged();
        } else {
          placemarkBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public Builder setPlacemark(
          co.viewfinder.proto.PlacemarkPB.Placemark.Builder builderForValue) {
        if (placemarkBuilder_ == null) {
          placemark_ = builderForValue.build();
          onChanged();
        } else {
          placemarkBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public Builder mergePlacemark(co.viewfinder.proto.PlacemarkPB.Placemark value) {
        if (placemarkBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              placemark_ != co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance()) {
            placemark_ =
              co.viewfinder.proto.PlacemarkPB.Placemark.newBuilder(placemark_).mergeFrom(value).buildPartial();
          } else {
            placemark_ = value;
          }
          onChanged();
        } else {
          placemarkBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public Builder clearPlacemark() {
        if (placemarkBuilder_ == null) {
          placemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
          onChanged();
        } else {
          placemarkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.Placemark.Builder getPlacemarkBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPlacemarkFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getPlacemarkOrBuilder() {
        if (placemarkBuilder_ != null) {
          return placemarkBuilder_.getMessageOrBuilder();
        } else {
          return placemark_;
        }
      }
      /**
       * <code>optional .Placemark placemark = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder> 
          getPlacemarkFieldBuilder() {
        if (placemarkBuilder_ == null) {
          placemarkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder>(
                  placemark_,
                  getParentForChildren(),
                  isClean());
          placemark_ = null;
        }
        return placemarkBuilder_;
      }

      // optional double timestamp = 3;
      private double timestamp_ ;
      /**
       * <code>optional double timestamp = 3;</code>
       *
       * <pre>
       * The time when the breadcrumb was gathered.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double timestamp = 3;</code>
       *
       * <pre>
       * The time when the breadcrumb was gathered.
       * </pre>
       */
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional double timestamp = 3;</code>
       *
       * <pre>
       * The time when the breadcrumb was gathered.
       * </pre>
       */
      public Builder setTimestamp(double value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double timestamp = 3;</code>
       *
       * <pre>
       * The time when the breadcrumb was gathered.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional string debug = 4;
      private java.lang.Object debug_ = "";
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public boolean hasDebug() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public java.lang.String getDebug() {
        java.lang.Object ref = debug_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          debug_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDebugBytes() {
        java.lang.Object ref = debug_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debug_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public Builder setDebug(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        debug_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public Builder clearDebug() {
        bitField0_ = (bitField0_ & ~0x00000008);
        debug_ = getDefaultInstance().getDebug();
        onChanged();
        return this;
      }
      /**
       * <code>optional string debug = 4;</code>
       *
       * <pre>
       * Additional non-programmatic data about the breadcrumb (e.g. app state when
       * the breadcrumb was gathered).
       * </pre>
       */
      public Builder setDebugBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        debug_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Breadcrumb)
    }

    static {
      defaultInstance = new Breadcrumb(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Breadcrumb)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Breadcrumb_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Breadcrumb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Breadcrumb.proto\032\016Location.proto\032\017Plac" +
      "emark.proto\"j\n\nBreadcrumb\022\033\n\010location\030\001 " +
      "\001(\0132\t.Location\022\035\n\tplacemark\030\002 \001(\0132\n.Plac" +
      "emark\022\021\n\ttimestamp\030\003 \001(\001\022\r\n\005debug\030\004 \001(\tB" +
      "#\n\023co.viewfinder.protoB\014BreadcrumbPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Breadcrumb_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Breadcrumb_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Breadcrumb_descriptor,
              new java.lang.String[] { "Location", "Placemark", "Timestamp", "Debug", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          co.viewfinder.proto.LocationPB.getDescriptor(),
          co.viewfinder.proto.PlacemarkPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
