// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EpisodeMetadata.proto

package co.viewfinder.proto;

public final class EpisodeMetadataPB {
  private EpisodeMetadataPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EpisodeMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .EpisodeId id = 1;
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    co.viewfinder.proto.ContentIdsPB.EpisodeId getId();
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getIdOrBuilder();

    // optional .EpisodeId parent_id = 2;
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    boolean hasParentId();
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    co.viewfinder.proto.ContentIdsPB.EpisodeId getParentId();
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getParentIdOrBuilder();

    // optional .ViewpointId viewpoint_id = 3;
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    boolean hasViewpointId();
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    co.viewfinder.proto.ContentIdsPB.ViewpointId getViewpointId();
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder getViewpointIdOrBuilder();

    // optional int64 user_id = 4;
    /**
     * <code>optional int64 user_id = 4;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 user_id = 4;</code>
     */
    long getUserId();

    // optional int64 sharing_user_id = 5;
    /**
     * <code>optional int64 sharing_user_id = 5;</code>
     */
    boolean hasSharingUserId();
    /**
     * <code>optional int64 sharing_user_id = 5;</code>
     */
    long getSharingUserId();

    // optional double timestamp = 6;
    /**
     * <code>optional double timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional double timestamp = 6;</code>
     */
    double getTimestamp();

    // optional double publish_timestamp = 12;
    /**
     * <code>optional double publish_timestamp = 12;</code>
     */
    boolean hasPublishTimestamp();
    /**
     * <code>optional double publish_timestamp = 12;</code>
     */
    double getPublishTimestamp();

    // optional string title = 7;
    /**
     * <code>optional string title = 7;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 7;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 7;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string description = 8;
    /**
     * <code>optional string description = 8;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 8;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 8;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // optional string name = 11;
    /**
     * <code>optional string name = 11;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 11;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 11;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional double earliest_photo_timestamp = 30;
    /**
     * <code>optional double earliest_photo_timestamp = 30;</code>
     *
     * <pre>
     * Client-side state.
     * </pre>
     */
    boolean hasEarliestPhotoTimestamp();
    /**
     * <code>optional double earliest_photo_timestamp = 30;</code>
     *
     * <pre>
     * Client-side state.
     * </pre>
     */
    double getEarliestPhotoTimestamp();

    // optional double latest_photo_timestamp = 31;
    /**
     * <code>optional double latest_photo_timestamp = 31;</code>
     */
    boolean hasLatestPhotoTimestamp();
    /**
     * <code>optional double latest_photo_timestamp = 31;</code>
     */
    double getLatestPhotoTimestamp();

    // optional bool upload_episode = 32;
    /**
     * <code>optional bool upload_episode = 32;</code>
     */
    boolean hasUploadEpisode();
    /**
     * <code>optional bool upload_episode = 32;</code>
     */
    boolean getUploadEpisode();

    // repeated string indexed_terms = 33;
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    java.util.List<java.lang.String>
    getIndexedTermsList();
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    int getIndexedTermsCount();
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    java.lang.String getIndexedTerms(int index);
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    com.google.protobuf.ByteString
        getIndexedTermsBytes(int index);

    // repeated string indexed_location_terms = 34;
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    java.util.List<java.lang.String>
    getIndexedLocationTermsList();
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    int getIndexedLocationTermsCount();
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    java.lang.String getIndexedLocationTerms(int index);
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    com.google.protobuf.ByteString
        getIndexedLocationTermsBytes(int index);

    // optional .Location DEPRECATED_location = 9;
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    boolean hasDEPRECATEDLocation();
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    co.viewfinder.proto.LocationPB.Location getDEPRECATEDLocation();
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    co.viewfinder.proto.LocationPB.LocationOrBuilder getDEPRECATEDLocationOrBuilder();

    // optional .Placemark DEPRECATED_placemark = 10;
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    boolean hasDEPRECATEDPlacemark();
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    co.viewfinder.proto.PlacemarkPB.Placemark getDEPRECATEDPlacemark();
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getDEPRECATEDPlacemarkOrBuilder();
  }
  /**
   * Protobuf type {@code EpisodeMetadata}
   */
  public static final class EpisodeMetadata extends
      com.google.protobuf.GeneratedMessage
      implements EpisodeMetadataOrBuilder {
    // Use EpisodeMetadata.newBuilder() to construct.
    private EpisodeMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EpisodeMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EpisodeMetadata defaultInstance;
    public static EpisodeMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public EpisodeMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EpisodeMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(co.viewfinder.proto.ContentIdsPB.EpisodeId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = parentId_.toBuilder();
              }
              parentId_ = input.readMessage(co.viewfinder.proto.ContentIdsPB.EpisodeId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(parentId_);
                parentId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = viewpointId_.toBuilder();
              }
              viewpointId_ = input.readMessage(co.viewfinder.proto.ContentIdsPB.ViewpointId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(viewpointId_);
                viewpointId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sharingUserId_ = input.readInt64();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readDouble();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000080;
              title_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000100;
              description_ = input.readBytes();
              break;
            }
            case 74: {
              co.viewfinder.proto.LocationPB.Location.Builder subBuilder = null;
              if (((bitField0_ & 0x00002000) == 0x00002000)) {
                subBuilder = dEPRECATEDLocation_.toBuilder();
              }
              dEPRECATEDLocation_ = input.readMessage(co.viewfinder.proto.LocationPB.Location.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dEPRECATEDLocation_);
                dEPRECATEDLocation_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00002000;
              break;
            }
            case 82: {
              co.viewfinder.proto.PlacemarkPB.Placemark.Builder subBuilder = null;
              if (((bitField0_ & 0x00004000) == 0x00004000)) {
                subBuilder = dEPRECATEDPlacemark_.toBuilder();
              }
              dEPRECATEDPlacemark_ = input.readMessage(co.viewfinder.proto.PlacemarkPB.Placemark.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dEPRECATEDPlacemark_);
                dEPRECATEDPlacemark_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00004000;
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              name_ = input.readBytes();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000040;
              publishTimestamp_ = input.readDouble();
              break;
            }
            case 241: {
              bitField0_ |= 0x00000400;
              earliestPhotoTimestamp_ = input.readDouble();
              break;
            }
            case 249: {
              bitField0_ |= 0x00000800;
              latestPhotoTimestamp_ = input.readDouble();
              break;
            }
            case 256: {
              bitField0_ |= 0x00001000;
              uploadEpisode_ = input.readBool();
              break;
            }
            case 266: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                indexedTerms_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00002000;
              }
              indexedTerms_.add(input.readBytes());
              break;
            }
            case 274: {
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                indexedLocationTerms_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00004000;
              }
              indexedLocationTerms_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
          indexedTerms_ = new com.google.protobuf.UnmodifiableLazyStringList(indexedTerms_);
        }
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          indexedLocationTerms_ = new com.google.protobuf.UnmodifiableLazyStringList(indexedLocationTerms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.EpisodeMetadataPB.internal_static_EpisodeMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.EpisodeMetadataPB.internal_static_EpisodeMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.class, co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<EpisodeMetadata> PARSER =
        new com.google.protobuf.AbstractParser<EpisodeMetadata>() {
      public EpisodeMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EpisodeMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EpisodeMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .EpisodeId id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private co.viewfinder.proto.ContentIdsPB.EpisodeId id_;
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.EpisodeId getId() {
      return id_;
    }
    /**
     * <code>optional .EpisodeId id = 1;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getIdOrBuilder() {
      return id_;
    }

    // optional .EpisodeId parent_id = 2;
    public static final int PARENT_ID_FIELD_NUMBER = 2;
    private co.viewfinder.proto.ContentIdsPB.EpisodeId parentId_;
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.EpisodeId getParentId() {
      return parentId_;
    }
    /**
     * <code>optional .EpisodeId parent_id = 2;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getParentIdOrBuilder() {
      return parentId_;
    }

    // optional .ViewpointId viewpoint_id = 3;
    public static final int VIEWPOINT_ID_FIELD_NUMBER = 3;
    private co.viewfinder.proto.ContentIdsPB.ViewpointId viewpointId_;
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    public boolean hasViewpointId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.ViewpointId getViewpointId() {
      return viewpointId_;
    }
    /**
     * <code>optional .ViewpointId viewpoint_id = 3;</code>
     */
    public co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder getViewpointIdOrBuilder() {
      return viewpointId_;
    }

    // optional int64 user_id = 4;
    public static final int USER_ID_FIELD_NUMBER = 4;
    private long userId_;
    /**
     * <code>optional int64 user_id = 4;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 user_id = 4;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // optional int64 sharing_user_id = 5;
    public static final int SHARING_USER_ID_FIELD_NUMBER = 5;
    private long sharingUserId_;
    /**
     * <code>optional int64 sharing_user_id = 5;</code>
     */
    public boolean hasSharingUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 sharing_user_id = 5;</code>
     */
    public long getSharingUserId() {
      return sharingUserId_;
    }

    // optional double timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private double timestamp_;
    /**
     * <code>optional double timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double timestamp = 6;</code>
     */
    public double getTimestamp() {
      return timestamp_;
    }

    // optional double publish_timestamp = 12;
    public static final int PUBLISH_TIMESTAMP_FIELD_NUMBER = 12;
    private double publishTimestamp_;
    /**
     * <code>optional double publish_timestamp = 12;</code>
     */
    public boolean hasPublishTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double publish_timestamp = 12;</code>
     */
    public double getPublishTimestamp() {
      return publishTimestamp_;
    }

    // optional string title = 7;
    public static final int TITLE_FIELD_NUMBER = 7;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 7;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string title = 7;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 8;
    public static final int DESCRIPTION_FIELD_NUMBER = 8;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 8;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string name = 11;
    public static final int NAME_FIELD_NUMBER = 11;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 11;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string name = 11;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double earliest_photo_timestamp = 30;
    public static final int EARLIEST_PHOTO_TIMESTAMP_FIELD_NUMBER = 30;
    private double earliestPhotoTimestamp_;
    /**
     * <code>optional double earliest_photo_timestamp = 30;</code>
     *
     * <pre>
     * Client-side state.
     * </pre>
     */
    public boolean hasEarliestPhotoTimestamp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional double earliest_photo_timestamp = 30;</code>
     *
     * <pre>
     * Client-side state.
     * </pre>
     */
    public double getEarliestPhotoTimestamp() {
      return earliestPhotoTimestamp_;
    }

    // optional double latest_photo_timestamp = 31;
    public static final int LATEST_PHOTO_TIMESTAMP_FIELD_NUMBER = 31;
    private double latestPhotoTimestamp_;
    /**
     * <code>optional double latest_photo_timestamp = 31;</code>
     */
    public boolean hasLatestPhotoTimestamp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional double latest_photo_timestamp = 31;</code>
     */
    public double getLatestPhotoTimestamp() {
      return latestPhotoTimestamp_;
    }

    // optional bool upload_episode = 32;
    public static final int UPLOAD_EPISODE_FIELD_NUMBER = 32;
    private boolean uploadEpisode_;
    /**
     * <code>optional bool upload_episode = 32;</code>
     */
    public boolean hasUploadEpisode() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bool upload_episode = 32;</code>
     */
    public boolean getUploadEpisode() {
      return uploadEpisode_;
    }

    // repeated string indexed_terms = 33;
    public static final int INDEXED_TERMS_FIELD_NUMBER = 33;
    private com.google.protobuf.LazyStringList indexedTerms_;
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    public java.util.List<java.lang.String>
        getIndexedTermsList() {
      return indexedTerms_;
    }
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    public int getIndexedTermsCount() {
      return indexedTerms_.size();
    }
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    public java.lang.String getIndexedTerms(int index) {
      return indexedTerms_.get(index);
    }
    /**
     * <code>repeated string indexed_terms = 33;</code>
     */
    public com.google.protobuf.ByteString
        getIndexedTermsBytes(int index) {
      return indexedTerms_.getByteString(index);
    }

    // repeated string indexed_location_terms = 34;
    public static final int INDEXED_LOCATION_TERMS_FIELD_NUMBER = 34;
    private com.google.protobuf.LazyStringList indexedLocationTerms_;
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    public java.util.List<java.lang.String>
        getIndexedLocationTermsList() {
      return indexedLocationTerms_;
    }
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    public int getIndexedLocationTermsCount() {
      return indexedLocationTerms_.size();
    }
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    public java.lang.String getIndexedLocationTerms(int index) {
      return indexedLocationTerms_.get(index);
    }
    /**
     * <code>repeated string indexed_location_terms = 34;</code>
     */
    public com.google.protobuf.ByteString
        getIndexedLocationTermsBytes(int index) {
      return indexedLocationTerms_.getByteString(index);
    }

    // optional .Location DEPRECATED_location = 9;
    public static final int DEPRECATED_LOCATION_FIELD_NUMBER = 9;
    private co.viewfinder.proto.LocationPB.Location dEPRECATEDLocation_;
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    public boolean hasDEPRECATEDLocation() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    public co.viewfinder.proto.LocationPB.Location getDEPRECATEDLocation() {
      return dEPRECATEDLocation_;
    }
    /**
     * <code>optional .Location DEPRECATED_location = 9;</code>
     */
    public co.viewfinder.proto.LocationPB.LocationOrBuilder getDEPRECATEDLocationOrBuilder() {
      return dEPRECATEDLocation_;
    }

    // optional .Placemark DEPRECATED_placemark = 10;
    public static final int DEPRECATED_PLACEMARK_FIELD_NUMBER = 10;
    private co.viewfinder.proto.PlacemarkPB.Placemark dEPRECATEDPlacemark_;
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    public boolean hasDEPRECATEDPlacemark() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    public co.viewfinder.proto.PlacemarkPB.Placemark getDEPRECATEDPlacemark() {
      return dEPRECATEDPlacemark_;
    }
    /**
     * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
     */
    public co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getDEPRECATEDPlacemarkOrBuilder() {
      return dEPRECATEDPlacemark_;
    }

    private void initFields() {
      id_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
      parentId_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
      viewpointId_ = co.viewfinder.proto.ContentIdsPB.ViewpointId.getDefaultInstance();
      userId_ = 0L;
      sharingUserId_ = 0L;
      timestamp_ = 0D;
      publishTimestamp_ = 0D;
      title_ = "";
      description_ = "";
      name_ = "";
      earliestPhotoTimestamp_ = 0D;
      latestPhotoTimestamp_ = 0D;
      uploadEpisode_ = false;
      indexedTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      indexedLocationTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dEPRECATEDLocation_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
      dEPRECATEDPlacemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, parentId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, viewpointId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, userId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, sharingUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, timestamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(8, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeMessage(9, dEPRECATEDLocation_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeMessage(10, dEPRECATEDPlacemark_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(12, publishTimestamp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeDouble(30, earliestPhotoTimestamp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeDouble(31, latestPhotoTimestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(32, uploadEpisode_);
      }
      for (int i = 0; i < indexedTerms_.size(); i++) {
        output.writeBytes(33, indexedTerms_.getByteString(i));
      }
      for (int i = 0; i < indexedLocationTerms_.size(); i++) {
        output.writeBytes(34, indexedLocationTerms_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, parentId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, viewpointId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, userId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sharingUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, timestamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, dEPRECATEDLocation_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, dEPRECATEDPlacemark_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, publishTimestamp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(30, earliestPhotoTimestamp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(31, latestPhotoTimestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(32, uploadEpisode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < indexedTerms_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(indexedTerms_.getByteString(i));
        }
        size += dataSize;
        size += 2 * getIndexedTermsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < indexedLocationTerms_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(indexedLocationTerms_.getByteString(i));
        }
        size += dataSize;
        size += 2 * getIndexedLocationTermsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EpisodeMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.EpisodeMetadataPB.internal_static_EpisodeMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.EpisodeMetadataPB.internal_static_EpisodeMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.class, co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.Builder.class);
      }

      // Construct using co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdFieldBuilder();
          getParentIdFieldBuilder();
          getViewpointIdFieldBuilder();
          getDEPRECATEDLocationFieldBuilder();
          getDEPRECATEDPlacemarkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (parentIdBuilder_ == null) {
          parentId_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
        } else {
          parentIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (viewpointIdBuilder_ == null) {
          viewpointId_ = co.viewfinder.proto.ContentIdsPB.ViewpointId.getDefaultInstance();
        } else {
          viewpointIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        sharingUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        publishTimestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        earliestPhotoTimestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        latestPhotoTimestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000800);
        uploadEpisode_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        indexedTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00002000);
        indexedLocationTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        if (dEPRECATEDLocationBuilder_ == null) {
          dEPRECATEDLocation_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
        } else {
          dEPRECATEDLocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          dEPRECATEDPlacemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
        } else {
          dEPRECATEDPlacemarkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.EpisodeMetadataPB.internal_static_EpisodeMetadata_descriptor;
      }

      public co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata getDefaultInstanceForType() {
        return co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.getDefaultInstance();
      }

      public co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata build() {
        co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata buildPartial() {
        co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata result = new co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (parentIdBuilder_ == null) {
          result.parentId_ = parentId_;
        } else {
          result.parentId_ = parentIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (viewpointIdBuilder_ == null) {
          result.viewpointId_ = viewpointId_;
        } else {
          result.viewpointId_ = viewpointIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sharingUserId_ = sharingUserId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.publishTimestamp_ = publishTimestamp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.earliestPhotoTimestamp_ = earliestPhotoTimestamp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.latestPhotoTimestamp_ = latestPhotoTimestamp_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.uploadEpisode_ = uploadEpisode_;
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          indexedTerms_ = new com.google.protobuf.UnmodifiableLazyStringList(
              indexedTerms_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.indexedTerms_ = indexedTerms_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          indexedLocationTerms_ = new com.google.protobuf.UnmodifiableLazyStringList(
              indexedLocationTerms_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.indexedLocationTerms_ = indexedLocationTerms_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00002000;
        }
        if (dEPRECATEDLocationBuilder_ == null) {
          result.dEPRECATEDLocation_ = dEPRECATEDLocation_;
        } else {
          result.dEPRECATEDLocation_ = dEPRECATEDLocationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00004000;
        }
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          result.dEPRECATEDPlacemark_ = dEPRECATEDPlacemark_;
        } else {
          result.dEPRECATEDPlacemark_ = dEPRECATEDPlacemarkBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata) {
          return mergeFrom((co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata other) {
        if (other == co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasParentId()) {
          mergeParentId(other.getParentId());
        }
        if (other.hasViewpointId()) {
          mergeViewpointId(other.getViewpointId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSharingUserId()) {
          setSharingUserId(other.getSharingUserId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasPublishTimestamp()) {
          setPublishTimestamp(other.getPublishTimestamp());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000080;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000100;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000200;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEarliestPhotoTimestamp()) {
          setEarliestPhotoTimestamp(other.getEarliestPhotoTimestamp());
        }
        if (other.hasLatestPhotoTimestamp()) {
          setLatestPhotoTimestamp(other.getLatestPhotoTimestamp());
        }
        if (other.hasUploadEpisode()) {
          setUploadEpisode(other.getUploadEpisode());
        }
        if (!other.indexedTerms_.isEmpty()) {
          if (indexedTerms_.isEmpty()) {
            indexedTerms_ = other.indexedTerms_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureIndexedTermsIsMutable();
            indexedTerms_.addAll(other.indexedTerms_);
          }
          onChanged();
        }
        if (!other.indexedLocationTerms_.isEmpty()) {
          if (indexedLocationTerms_.isEmpty()) {
            indexedLocationTerms_ = other.indexedLocationTerms_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureIndexedLocationTermsIsMutable();
            indexedLocationTerms_.addAll(other.indexedLocationTerms_);
          }
          onChanged();
        }
        if (other.hasDEPRECATEDLocation()) {
          mergeDEPRECATEDLocation(other.getDEPRECATEDLocation());
        }
        if (other.hasDEPRECATEDPlacemark()) {
          mergeDEPRECATEDPlacemark(other.getDEPRECATEDPlacemark());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.EpisodeMetadataPB.EpisodeMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .EpisodeId id = 1;
      private co.viewfinder.proto.ContentIdsPB.EpisodeId id_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder> idBuilder_;
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeId getId() {
        if (idBuilder_ == null) {
          return id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public Builder setId(co.viewfinder.proto.ContentIdsPB.EpisodeId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public Builder setId(
          co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public Builder mergeId(co.viewfinder.proto.ContentIdsPB.EpisodeId value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              id_ != co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance()) {
            id_ =
              co.viewfinder.proto.ContentIdsPB.EpisodeId.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_;
        }
      }
      /**
       * <code>optional .EpisodeId id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder>(
                  id_,
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      // optional .EpisodeId parent_id = 2;
      private co.viewfinder.proto.ContentIdsPB.EpisodeId parentId_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder> parentIdBuilder_;
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeId getParentId() {
        if (parentIdBuilder_ == null) {
          return parentId_;
        } else {
          return parentIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public Builder setParentId(co.viewfinder.proto.ContentIdsPB.EpisodeId value) {
        if (parentIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parentId_ = value;
          onChanged();
        } else {
          parentIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public Builder setParentId(
          co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder builderForValue) {
        if (parentIdBuilder_ == null) {
          parentId_ = builderForValue.build();
          onChanged();
        } else {
          parentIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public Builder mergeParentId(co.viewfinder.proto.ContentIdsPB.EpisodeId value) {
        if (parentIdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              parentId_ != co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance()) {
            parentId_ =
              co.viewfinder.proto.ContentIdsPB.EpisodeId.newBuilder(parentId_).mergeFrom(value).buildPartial();
          } else {
            parentId_ = value;
          }
          onChanged();
        } else {
          parentIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public Builder clearParentId() {
        if (parentIdBuilder_ == null) {
          parentId_ = co.viewfinder.proto.ContentIdsPB.EpisodeId.getDefaultInstance();
          onChanged();
        } else {
          parentIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder getParentIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParentIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder getParentIdOrBuilder() {
        if (parentIdBuilder_ != null) {
          return parentIdBuilder_.getMessageOrBuilder();
        } else {
          return parentId_;
        }
      }
      /**
       * <code>optional .EpisodeId parent_id = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder> 
          getParentIdFieldBuilder() {
        if (parentIdBuilder_ == null) {
          parentIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.ContentIdsPB.EpisodeId, co.viewfinder.proto.ContentIdsPB.EpisodeId.Builder, co.viewfinder.proto.ContentIdsPB.EpisodeIdOrBuilder>(
                  parentId_,
                  getParentForChildren(),
                  isClean());
          parentId_ = null;
        }
        return parentIdBuilder_;
      }

      // optional .ViewpointId viewpoint_id = 3;
      private co.viewfinder.proto.ContentIdsPB.ViewpointId viewpointId_ = co.viewfinder.proto.ContentIdsPB.ViewpointId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.ViewpointId, co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder, co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder> viewpointIdBuilder_;
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public boolean hasViewpointId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.ViewpointId getViewpointId() {
        if (viewpointIdBuilder_ == null) {
          return viewpointId_;
        } else {
          return viewpointIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public Builder setViewpointId(co.viewfinder.proto.ContentIdsPB.ViewpointId value) {
        if (viewpointIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          viewpointId_ = value;
          onChanged();
        } else {
          viewpointIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public Builder setViewpointId(
          co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder builderForValue) {
        if (viewpointIdBuilder_ == null) {
          viewpointId_ = builderForValue.build();
          onChanged();
        } else {
          viewpointIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public Builder mergeViewpointId(co.viewfinder.proto.ContentIdsPB.ViewpointId value) {
        if (viewpointIdBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              viewpointId_ != co.viewfinder.proto.ContentIdsPB.ViewpointId.getDefaultInstance()) {
            viewpointId_ =
              co.viewfinder.proto.ContentIdsPB.ViewpointId.newBuilder(viewpointId_).mergeFrom(value).buildPartial();
          } else {
            viewpointId_ = value;
          }
          onChanged();
        } else {
          viewpointIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public Builder clearViewpointId() {
        if (viewpointIdBuilder_ == null) {
          viewpointId_ = co.viewfinder.proto.ContentIdsPB.ViewpointId.getDefaultInstance();
          onChanged();
        } else {
          viewpointIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder getViewpointIdBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getViewpointIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      public co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder getViewpointIdOrBuilder() {
        if (viewpointIdBuilder_ != null) {
          return viewpointIdBuilder_.getMessageOrBuilder();
        } else {
          return viewpointId_;
        }
      }
      /**
       * <code>optional .ViewpointId viewpoint_id = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.ContentIdsPB.ViewpointId, co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder, co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder> 
          getViewpointIdFieldBuilder() {
        if (viewpointIdBuilder_ == null) {
          viewpointIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.ContentIdsPB.ViewpointId, co.viewfinder.proto.ContentIdsPB.ViewpointId.Builder, co.viewfinder.proto.ContentIdsPB.ViewpointIdOrBuilder>(
                  viewpointId_,
                  getParentForChildren(),
                  isClean());
          viewpointId_ = null;
        }
        return viewpointIdBuilder_;
      }

      // optional int64 user_id = 4;
      private long userId_ ;
      /**
       * <code>optional int64 user_id = 4;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 user_id = 4;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 user_id = 4;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 user_id = 4;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 sharing_user_id = 5;
      private long sharingUserId_ ;
      /**
       * <code>optional int64 sharing_user_id = 5;</code>
       */
      public boolean hasSharingUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 sharing_user_id = 5;</code>
       */
      public long getSharingUserId() {
        return sharingUserId_;
      }
      /**
       * <code>optional int64 sharing_user_id = 5;</code>
       */
      public Builder setSharingUserId(long value) {
        bitField0_ |= 0x00000010;
        sharingUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sharing_user_id = 5;</code>
       */
      public Builder clearSharingUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sharingUserId_ = 0L;
        onChanged();
        return this;
      }

      // optional double timestamp = 6;
      private double timestamp_ ;
      /**
       * <code>optional double timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double timestamp = 6;</code>
       */
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional double timestamp = 6;</code>
       */
      public Builder setTimestamp(double value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional double publish_timestamp = 12;
      private double publishTimestamp_ ;
      /**
       * <code>optional double publish_timestamp = 12;</code>
       */
      public boolean hasPublishTimestamp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double publish_timestamp = 12;</code>
       */
      public double getPublishTimestamp() {
        return publishTimestamp_;
      }
      /**
       * <code>optional double publish_timestamp = 12;</code>
       */
      public Builder setPublishTimestamp(double value) {
        bitField0_ |= 0x00000040;
        publishTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double publish_timestamp = 12;</code>
       */
      public Builder clearPublishTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        publishTimestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional string title = 7;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 7;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string title = 7;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 7;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 7;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000080);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 7;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        title_ = value;
        onChanged();
        return this;
      }

      // optional string description = 8;
      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 8;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000100);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        description_ = value;
        onChanged();
        return this;
      }

      // optional string name = 11;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 11;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string name = 11;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 11;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 11;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 11;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000200);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 11;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        name_ = value;
        onChanged();
        return this;
      }

      // optional double earliest_photo_timestamp = 30;
      private double earliestPhotoTimestamp_ ;
      /**
       * <code>optional double earliest_photo_timestamp = 30;</code>
       *
       * <pre>
       * Client-side state.
       * </pre>
       */
      public boolean hasEarliestPhotoTimestamp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double earliest_photo_timestamp = 30;</code>
       *
       * <pre>
       * Client-side state.
       * </pre>
       */
      public double getEarliestPhotoTimestamp() {
        return earliestPhotoTimestamp_;
      }
      /**
       * <code>optional double earliest_photo_timestamp = 30;</code>
       *
       * <pre>
       * Client-side state.
       * </pre>
       */
      public Builder setEarliestPhotoTimestamp(double value) {
        bitField0_ |= 0x00000400;
        earliestPhotoTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double earliest_photo_timestamp = 30;</code>
       *
       * <pre>
       * Client-side state.
       * </pre>
       */
      public Builder clearEarliestPhotoTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        earliestPhotoTimestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional double latest_photo_timestamp = 31;
      private double latestPhotoTimestamp_ ;
      /**
       * <code>optional double latest_photo_timestamp = 31;</code>
       */
      public boolean hasLatestPhotoTimestamp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional double latest_photo_timestamp = 31;</code>
       */
      public double getLatestPhotoTimestamp() {
        return latestPhotoTimestamp_;
      }
      /**
       * <code>optional double latest_photo_timestamp = 31;</code>
       */
      public Builder setLatestPhotoTimestamp(double value) {
        bitField0_ |= 0x00000800;
        latestPhotoTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latest_photo_timestamp = 31;</code>
       */
      public Builder clearLatestPhotoTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000800);
        latestPhotoTimestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional bool upload_episode = 32;
      private boolean uploadEpisode_ ;
      /**
       * <code>optional bool upload_episode = 32;</code>
       */
      public boolean hasUploadEpisode() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bool upload_episode = 32;</code>
       */
      public boolean getUploadEpisode() {
        return uploadEpisode_;
      }
      /**
       * <code>optional bool upload_episode = 32;</code>
       */
      public Builder setUploadEpisode(boolean value) {
        bitField0_ |= 0x00001000;
        uploadEpisode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool upload_episode = 32;</code>
       */
      public Builder clearUploadEpisode() {
        bitField0_ = (bitField0_ & ~0x00001000);
        uploadEpisode_ = false;
        onChanged();
        return this;
      }

      // repeated string indexed_terms = 33;
      private com.google.protobuf.LazyStringList indexedTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndexedTermsIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          indexedTerms_ = new com.google.protobuf.LazyStringArrayList(indexedTerms_);
          bitField0_ |= 0x00002000;
         }
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public java.util.List<java.lang.String>
          getIndexedTermsList() {
        return java.util.Collections.unmodifiableList(indexedTerms_);
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public int getIndexedTermsCount() {
        return indexedTerms_.size();
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public java.lang.String getIndexedTerms(int index) {
        return indexedTerms_.get(index);
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public com.google.protobuf.ByteString
          getIndexedTermsBytes(int index) {
        return indexedTerms_.getByteString(index);
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public Builder setIndexedTerms(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedTermsIsMutable();
        indexedTerms_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public Builder addIndexedTerms(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedTermsIsMutable();
        indexedTerms_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public Builder addAllIndexedTerms(
          java.lang.Iterable<java.lang.String> values) {
        ensureIndexedTermsIsMutable();
        super.addAll(values, indexedTerms_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public Builder clearIndexedTerms() {
        indexedTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_terms = 33;</code>
       */
      public Builder addIndexedTermsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedTermsIsMutable();
        indexedTerms_.add(value);
        onChanged();
        return this;
      }

      // repeated string indexed_location_terms = 34;
      private com.google.protobuf.LazyStringList indexedLocationTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndexedLocationTermsIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          indexedLocationTerms_ = new com.google.protobuf.LazyStringArrayList(indexedLocationTerms_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public java.util.List<java.lang.String>
          getIndexedLocationTermsList() {
        return java.util.Collections.unmodifiableList(indexedLocationTerms_);
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public int getIndexedLocationTermsCount() {
        return indexedLocationTerms_.size();
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public java.lang.String getIndexedLocationTerms(int index) {
        return indexedLocationTerms_.get(index);
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public com.google.protobuf.ByteString
          getIndexedLocationTermsBytes(int index) {
        return indexedLocationTerms_.getByteString(index);
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public Builder setIndexedLocationTerms(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedLocationTermsIsMutable();
        indexedLocationTerms_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public Builder addIndexedLocationTerms(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedLocationTermsIsMutable();
        indexedLocationTerms_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public Builder addAllIndexedLocationTerms(
          java.lang.Iterable<java.lang.String> values) {
        ensureIndexedLocationTermsIsMutable();
        super.addAll(values, indexedLocationTerms_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public Builder clearIndexedLocationTerms() {
        indexedLocationTerms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string indexed_location_terms = 34;</code>
       */
      public Builder addIndexedLocationTermsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndexedLocationTermsIsMutable();
        indexedLocationTerms_.add(value);
        onChanged();
        return this;
      }

      // optional .Location DEPRECATED_location = 9;
      private co.viewfinder.proto.LocationPB.Location dEPRECATEDLocation_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder> dEPRECATEDLocationBuilder_;
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public boolean hasDEPRECATEDLocation() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public co.viewfinder.proto.LocationPB.Location getDEPRECATEDLocation() {
        if (dEPRECATEDLocationBuilder_ == null) {
          return dEPRECATEDLocation_;
        } else {
          return dEPRECATEDLocationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public Builder setDEPRECATEDLocation(co.viewfinder.proto.LocationPB.Location value) {
        if (dEPRECATEDLocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dEPRECATEDLocation_ = value;
          onChanged();
        } else {
          dEPRECATEDLocationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public Builder setDEPRECATEDLocation(
          co.viewfinder.proto.LocationPB.Location.Builder builderForValue) {
        if (dEPRECATEDLocationBuilder_ == null) {
          dEPRECATEDLocation_ = builderForValue.build();
          onChanged();
        } else {
          dEPRECATEDLocationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public Builder mergeDEPRECATEDLocation(co.viewfinder.proto.LocationPB.Location value) {
        if (dEPRECATEDLocationBuilder_ == null) {
          if (((bitField0_ & 0x00008000) == 0x00008000) &&
              dEPRECATEDLocation_ != co.viewfinder.proto.LocationPB.Location.getDefaultInstance()) {
            dEPRECATEDLocation_ =
              co.viewfinder.proto.LocationPB.Location.newBuilder(dEPRECATEDLocation_).mergeFrom(value).buildPartial();
          } else {
            dEPRECATEDLocation_ = value;
          }
          onChanged();
        } else {
          dEPRECATEDLocationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public Builder clearDEPRECATEDLocation() {
        if (dEPRECATEDLocationBuilder_ == null) {
          dEPRECATEDLocation_ = co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
          onChanged();
        } else {
          dEPRECATEDLocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public co.viewfinder.proto.LocationPB.Location.Builder getDEPRECATEDLocationBuilder() {
        bitField0_ |= 0x00008000;
        onChanged();
        return getDEPRECATEDLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      public co.viewfinder.proto.LocationPB.LocationOrBuilder getDEPRECATEDLocationOrBuilder() {
        if (dEPRECATEDLocationBuilder_ != null) {
          return dEPRECATEDLocationBuilder_.getMessageOrBuilder();
        } else {
          return dEPRECATEDLocation_;
        }
      }
      /**
       * <code>optional .Location DEPRECATED_location = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder> 
          getDEPRECATEDLocationFieldBuilder() {
        if (dEPRECATEDLocationBuilder_ == null) {
          dEPRECATEDLocationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.LocationPB.Location, co.viewfinder.proto.LocationPB.Location.Builder, co.viewfinder.proto.LocationPB.LocationOrBuilder>(
                  dEPRECATEDLocation_,
                  getParentForChildren(),
                  isClean());
          dEPRECATEDLocation_ = null;
        }
        return dEPRECATEDLocationBuilder_;
      }

      // optional .Placemark DEPRECATED_placemark = 10;
      private co.viewfinder.proto.PlacemarkPB.Placemark dEPRECATEDPlacemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder> dEPRECATEDPlacemarkBuilder_;
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public boolean hasDEPRECATEDPlacemark() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.Placemark getDEPRECATEDPlacemark() {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          return dEPRECATEDPlacemark_;
        } else {
          return dEPRECATEDPlacemarkBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public Builder setDEPRECATEDPlacemark(co.viewfinder.proto.PlacemarkPB.Placemark value) {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dEPRECATEDPlacemark_ = value;
          onChanged();
        } else {
          dEPRECATEDPlacemarkBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public Builder setDEPRECATEDPlacemark(
          co.viewfinder.proto.PlacemarkPB.Placemark.Builder builderForValue) {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          dEPRECATEDPlacemark_ = builderForValue.build();
          onChanged();
        } else {
          dEPRECATEDPlacemarkBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public Builder mergeDEPRECATEDPlacemark(co.viewfinder.proto.PlacemarkPB.Placemark value) {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          if (((bitField0_ & 0x00010000) == 0x00010000) &&
              dEPRECATEDPlacemark_ != co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance()) {
            dEPRECATEDPlacemark_ =
              co.viewfinder.proto.PlacemarkPB.Placemark.newBuilder(dEPRECATEDPlacemark_).mergeFrom(value).buildPartial();
          } else {
            dEPRECATEDPlacemark_ = value;
          }
          onChanged();
        } else {
          dEPRECATEDPlacemarkBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public Builder clearDEPRECATEDPlacemark() {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          dEPRECATEDPlacemark_ = co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
          onChanged();
        } else {
          dEPRECATEDPlacemarkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.Placemark.Builder getDEPRECATEDPlacemarkBuilder() {
        bitField0_ |= 0x00010000;
        onChanged();
        return getDEPRECATEDPlacemarkFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      public co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder getDEPRECATEDPlacemarkOrBuilder() {
        if (dEPRECATEDPlacemarkBuilder_ != null) {
          return dEPRECATEDPlacemarkBuilder_.getMessageOrBuilder();
        } else {
          return dEPRECATEDPlacemark_;
        }
      }
      /**
       * <code>optional .Placemark DEPRECATED_placemark = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder> 
          getDEPRECATEDPlacemarkFieldBuilder() {
        if (dEPRECATEDPlacemarkBuilder_ == null) {
          dEPRECATEDPlacemarkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              co.viewfinder.proto.PlacemarkPB.Placemark, co.viewfinder.proto.PlacemarkPB.Placemark.Builder, co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder>(
                  dEPRECATEDPlacemark_,
                  getParentForChildren(),
                  isClean());
          dEPRECATEDPlacemark_ = null;
        }
        return dEPRECATEDPlacemarkBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EpisodeMetadata)
    }

    static {
      defaultInstance = new EpisodeMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EpisodeMetadata)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EpisodeMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EpisodeMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EpisodeMetadata.proto\032\020ContentIds.prot" +
      "o\032\025ContactMetadata.proto\032\016Location.proto" +
      "\032\017Placemark.proto\"\331\003\n\017EpisodeMetadata\022\026\n" +
      "\002id\030\001 \001(\0132\n.EpisodeId\022\035\n\tparent_id\030\002 \001(\013" +
      "2\n.EpisodeId\022\"\n\014viewpoint_id\030\003 \001(\0132\014.Vie" +
      "wpointId\022\017\n\007user_id\030\004 \001(\003\022\027\n\017sharing_use" +
      "r_id\030\005 \001(\003\022\021\n\ttimestamp\030\006 \001(\001\022\031\n\021publish" +
      "_timestamp\030\014 \001(\001\022\r\n\005title\030\007 \001(\t\022\023\n\013descr" +
      "iption\030\010 \001(\t\022\014\n\004name\030\013 \001(\t\022 \n\030earliest_p" +
      "hoto_timestamp\030\036 \001(\001\022\036\n\026latest_photo_tim",
      "estamp\030\037 \001(\001\022\026\n\016upload_episode\030  \001(\010\022\025\n\r" +
      "indexed_terms\030! \003(\t\022\036\n\026indexed_location_" +
      "terms\030\" \003(\t\022&\n\023DEPRECATED_location\030\t \001(\013" +
      "2\t.Location\022(\n\024DEPRECATED_placemark\030\n \001(" +
      "\0132\n.PlacemarkB(\n\023co.viewfinder.protoB\021Ep" +
      "isodeMetadataPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EpisodeMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EpisodeMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EpisodeMetadata_descriptor,
              new java.lang.String[] { "Id", "ParentId", "ViewpointId", "UserId", "SharingUserId", "Timestamp", "PublishTimestamp", "Title", "Description", "Name", "EarliestPhotoTimestamp", "LatestPhotoTimestamp", "UploadEpisode", "IndexedTerms", "IndexedLocationTerms", "DEPRECATEDLocation", "DEPRECATEDPlacemark", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          co.viewfinder.proto.ContentIdsPB.getDescriptor(),
          co.viewfinder.proto.ContactMetadataPB.getDescriptor(),
          co.viewfinder.proto.LocationPB.getDescriptor(),
          co.viewfinder.proto.PlacemarkPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
