// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerGroup.proto

package co.viewfinder.proto;

public final class FollowerGroupPB {
  private FollowerGroupPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FollowerGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 user_ids = 1;
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    java.util.List<java.lang.Long> getUserIdsList();
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    int getUserIdsCount();
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    long getUserIds(int index);

    // repeated .FollowerGroup.ViewpointInfo viewpoints = 2;
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> 
        getViewpointsList();
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo getViewpoints(int index);
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    int getViewpointsCount();
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    java.util.List<? extends co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder> 
        getViewpointsOrBuilderList();
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder getViewpointsOrBuilder(
        int index);

    // optional double weight = 3;
    /**
     * <code>optional double weight = 3;</code>
     *
     * <pre>
     * Group weight. Computed in-process and not persisted.
     * </pre>
     */
    boolean hasWeight();
    /**
     * <code>optional double weight = 3;</code>
     *
     * <pre>
     * Group weight. Computed in-process and not persisted.
     * </pre>
     */
    double getWeight();
  }
  /**
   * Protobuf type {@code FollowerGroup}
   */
  public static final class FollowerGroup extends
      com.google.protobuf.GeneratedMessage
      implements FollowerGroupOrBuilder {
    // Use FollowerGroup.newBuilder() to construct.
    private FollowerGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FollowerGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FollowerGroup defaultInstance;
    public static FollowerGroup getDefaultInstance() {
      return defaultInstance;
    }

    public FollowerGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FollowerGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              userIds_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                userIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                userIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                viewpoints_ = new java.util.ArrayList<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              viewpoints_.add(input.readMessage(co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.PARSER, extensionRegistry));
              break;
            }
            case 25: {
              bitField0_ |= 0x00000001;
              weight_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userIds_ = java.util.Collections.unmodifiableList(userIds_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          viewpoints_ = java.util.Collections.unmodifiableList(viewpoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.FollowerGroupPB.FollowerGroup.class, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<FollowerGroup> PARSER =
        new com.google.protobuf.AbstractParser<FollowerGroup>() {
      public FollowerGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FollowerGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FollowerGroup> getParserForType() {
      return PARSER;
    }

    public interface ViewpointInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int64 viewpoint_id = 1;
      /**
       * <code>optional int64 viewpoint_id = 1;</code>
       */
      boolean hasViewpointId();
      /**
       * <code>optional int64 viewpoint_id = 1;</code>
       */
      long getViewpointId();

      // optional double earliest_timestamp = 2;
      /**
       * <code>optional double earliest_timestamp = 2;</code>
       */
      boolean hasEarliestTimestamp();
      /**
       * <code>optional double earliest_timestamp = 2;</code>
       */
      double getEarliestTimestamp();

      // optional double latest_timestamp = 3;
      /**
       * <code>optional double latest_timestamp = 3;</code>
       */
      boolean hasLatestTimestamp();
      /**
       * <code>optional double latest_timestamp = 3;</code>
       */
      double getLatestTimestamp();

      // optional double weight = 4;
      /**
       * <code>optional double weight = 4;</code>
       */
      boolean hasWeight();
      /**
       * <code>optional double weight = 4;</code>
       */
      double getWeight();
    }
    /**
     * Protobuf type {@code FollowerGroup.ViewpointInfo}
     *
     * <pre>
     * Information about each viewpoint followed by this group.
     * </pre>
     */
    public static final class ViewpointInfo extends
        com.google.protobuf.GeneratedMessage
        implements ViewpointInfoOrBuilder {
      // Use ViewpointInfo.newBuilder() to construct.
      private ViewpointInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ViewpointInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ViewpointInfo defaultInstance;
      public static ViewpointInfo getDefaultInstance() {
        return defaultInstance;
      }

      public ViewpointInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ViewpointInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                viewpointId_ = input.readInt64();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                earliestTimestamp_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                latestTimestamp_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                weight_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_ViewpointInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_ViewpointInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.class, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<ViewpointInfo> PARSER =
          new com.google.protobuf.AbstractParser<ViewpointInfo>() {
        public ViewpointInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ViewpointInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ViewpointInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int64 viewpoint_id = 1;
      public static final int VIEWPOINT_ID_FIELD_NUMBER = 1;
      private long viewpointId_;
      /**
       * <code>optional int64 viewpoint_id = 1;</code>
       */
      public boolean hasViewpointId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 viewpoint_id = 1;</code>
       */
      public long getViewpointId() {
        return viewpointId_;
      }

      // optional double earliest_timestamp = 2;
      public static final int EARLIEST_TIMESTAMP_FIELD_NUMBER = 2;
      private double earliestTimestamp_;
      /**
       * <code>optional double earliest_timestamp = 2;</code>
       */
      public boolean hasEarliestTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double earliest_timestamp = 2;</code>
       */
      public double getEarliestTimestamp() {
        return earliestTimestamp_;
      }

      // optional double latest_timestamp = 3;
      public static final int LATEST_TIMESTAMP_FIELD_NUMBER = 3;
      private double latestTimestamp_;
      /**
       * <code>optional double latest_timestamp = 3;</code>
       */
      public boolean hasLatestTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double latest_timestamp = 3;</code>
       */
      public double getLatestTimestamp() {
        return latestTimestamp_;
      }

      // optional double weight = 4;
      public static final int WEIGHT_FIELD_NUMBER = 4;
      private double weight_;
      /**
       * <code>optional double weight = 4;</code>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double weight = 4;</code>
       */
      public double getWeight() {
        return weight_;
      }

      private void initFields() {
        viewpointId_ = 0L;
        earliestTimestamp_ = 0D;
        latestTimestamp_ = 0D;
        weight_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, viewpointId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, earliestTimestamp_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, latestTimestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, weight_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, viewpointId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, earliestTimestamp_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, latestTimestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, weight_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code FollowerGroup.ViewpointInfo}
       *
       * <pre>
       * Information about each viewpoint followed by this group.
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_ViewpointInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_ViewpointInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.class, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder.class);
        }

        // Construct using co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          viewpointId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          earliestTimestamp_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          latestTimestamp_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          weight_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_ViewpointInfo_descriptor;
        }

        public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo getDefaultInstanceForType() {
          return co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.getDefaultInstance();
        }

        public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo build() {
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo buildPartial() {
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo result = new co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.viewpointId_ = viewpointId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.earliestTimestamp_ = earliestTimestamp_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.latestTimestamp_ = latestTimestamp_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.weight_ = weight_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo) {
            return mergeFrom((co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo other) {
          if (other == co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.getDefaultInstance()) return this;
          if (other.hasViewpointId()) {
            setViewpointId(other.getViewpointId());
          }
          if (other.hasEarliestTimestamp()) {
            setEarliestTimestamp(other.getEarliestTimestamp());
          }
          if (other.hasLatestTimestamp()) {
            setLatestTimestamp(other.getLatestTimestamp());
          }
          if (other.hasWeight()) {
            setWeight(other.getWeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int64 viewpoint_id = 1;
        private long viewpointId_ ;
        /**
         * <code>optional int64 viewpoint_id = 1;</code>
         */
        public boolean hasViewpointId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int64 viewpoint_id = 1;</code>
         */
        public long getViewpointId() {
          return viewpointId_;
        }
        /**
         * <code>optional int64 viewpoint_id = 1;</code>
         */
        public Builder setViewpointId(long value) {
          bitField0_ |= 0x00000001;
          viewpointId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 viewpoint_id = 1;</code>
         */
        public Builder clearViewpointId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          viewpointId_ = 0L;
          onChanged();
          return this;
        }

        // optional double earliest_timestamp = 2;
        private double earliestTimestamp_ ;
        /**
         * <code>optional double earliest_timestamp = 2;</code>
         */
        public boolean hasEarliestTimestamp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional double earliest_timestamp = 2;</code>
         */
        public double getEarliestTimestamp() {
          return earliestTimestamp_;
        }
        /**
         * <code>optional double earliest_timestamp = 2;</code>
         */
        public Builder setEarliestTimestamp(double value) {
          bitField0_ |= 0x00000002;
          earliestTimestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double earliest_timestamp = 2;</code>
         */
        public Builder clearEarliestTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          earliestTimestamp_ = 0D;
          onChanged();
          return this;
        }

        // optional double latest_timestamp = 3;
        private double latestTimestamp_ ;
        /**
         * <code>optional double latest_timestamp = 3;</code>
         */
        public boolean hasLatestTimestamp() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional double latest_timestamp = 3;</code>
         */
        public double getLatestTimestamp() {
          return latestTimestamp_;
        }
        /**
         * <code>optional double latest_timestamp = 3;</code>
         */
        public Builder setLatestTimestamp(double value) {
          bitField0_ |= 0x00000004;
          latestTimestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double latest_timestamp = 3;</code>
         */
        public Builder clearLatestTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000004);
          latestTimestamp_ = 0D;
          onChanged();
          return this;
        }

        // optional double weight = 4;
        private double weight_ ;
        /**
         * <code>optional double weight = 4;</code>
         */
        public boolean hasWeight() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional double weight = 4;</code>
         */
        public double getWeight() {
          return weight_;
        }
        /**
         * <code>optional double weight = 4;</code>
         */
        public Builder setWeight(double value) {
          bitField0_ |= 0x00000008;
          weight_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double weight = 4;</code>
         */
        public Builder clearWeight() {
          bitField0_ = (bitField0_ & ~0x00000008);
          weight_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:FollowerGroup.ViewpointInfo)
      }

      static {
        defaultInstance = new ViewpointInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:FollowerGroup.ViewpointInfo)
    }

    private int bitField0_;
    // repeated int64 user_ids = 1;
    public static final int USER_IDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> userIds_;
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getUserIdsList() {
      return userIds_;
    }
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    public int getUserIdsCount() {
      return userIds_.size();
    }
    /**
     * <code>repeated int64 user_ids = 1;</code>
     *
     * <pre>
     * List of user ids in the follower group. Sorted in ascending order.
     * </pre>
     */
    public long getUserIds(int index) {
      return userIds_.get(index);
    }

    // repeated .FollowerGroup.ViewpointInfo viewpoints = 2;
    public static final int VIEWPOINTS_FIELD_NUMBER = 2;
    private java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> viewpoints_;
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    public java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> getViewpointsList() {
      return viewpoints_;
    }
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    public java.util.List<? extends co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder> 
        getViewpointsOrBuilderList() {
      return viewpoints_;
    }
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    public int getViewpointsCount() {
      return viewpoints_.size();
    }
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo getViewpoints(int index) {
      return viewpoints_.get(index);
    }
    /**
     * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
     *
     * <pre>
     * List of viewpoints, sorted by viewpoint id.
     * </pre>
     */
    public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder getViewpointsOrBuilder(
        int index) {
      return viewpoints_.get(index);
    }

    // optional double weight = 3;
    public static final int WEIGHT_FIELD_NUMBER = 3;
    private double weight_;
    /**
     * <code>optional double weight = 3;</code>
     *
     * <pre>
     * Group weight. Computed in-process and not persisted.
     * </pre>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double weight = 3;</code>
     *
     * <pre>
     * Group weight. Computed in-process and not persisted.
     * </pre>
     */
    public double getWeight() {
      return weight_;
    }

    private void initFields() {
      userIds_ = java.util.Collections.emptyList();
      viewpoints_ = java.util.Collections.emptyList();
      weight_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userIds_.size(); i++) {
        output.writeInt64(1, userIds_.get(i));
      }
      for (int i = 0; i < viewpoints_.size(); i++) {
        output.writeMessage(2, viewpoints_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(3, weight_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < userIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(userIds_.get(i));
        }
        size += dataSize;
        size += 1 * getUserIdsList().size();
      }
      for (int i = 0; i < viewpoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, viewpoints_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, weight_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.FollowerGroupPB.FollowerGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.FollowerGroupPB.FollowerGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FollowerGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.FollowerGroupPB.FollowerGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.FollowerGroupPB.FollowerGroup.class, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.Builder.class);
      }

      // Construct using co.viewfinder.proto.FollowerGroupPB.FollowerGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getViewpointsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (viewpointsBuilder_ == null) {
          viewpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          viewpointsBuilder_.clear();
        }
        weight_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.FollowerGroupPB.internal_static_FollowerGroup_descriptor;
      }

      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup getDefaultInstanceForType() {
        return co.viewfinder.proto.FollowerGroupPB.FollowerGroup.getDefaultInstance();
      }

      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup build() {
        co.viewfinder.proto.FollowerGroupPB.FollowerGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup buildPartial() {
        co.viewfinder.proto.FollowerGroupPB.FollowerGroup result = new co.viewfinder.proto.FollowerGroupPB.FollowerGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userIds_ = java.util.Collections.unmodifiableList(userIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userIds_ = userIds_;
        if (viewpointsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            viewpoints_ = java.util.Collections.unmodifiableList(viewpoints_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.viewpoints_ = viewpoints_;
        } else {
          result.viewpoints_ = viewpointsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.weight_ = weight_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.FollowerGroupPB.FollowerGroup) {
          return mergeFrom((co.viewfinder.proto.FollowerGroupPB.FollowerGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.FollowerGroupPB.FollowerGroup other) {
        if (other == co.viewfinder.proto.FollowerGroupPB.FollowerGroup.getDefaultInstance()) return this;
        if (!other.userIds_.isEmpty()) {
          if (userIds_.isEmpty()) {
            userIds_ = other.userIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserIdsIsMutable();
            userIds_.addAll(other.userIds_);
          }
          onChanged();
        }
        if (viewpointsBuilder_ == null) {
          if (!other.viewpoints_.isEmpty()) {
            if (viewpoints_.isEmpty()) {
              viewpoints_ = other.viewpoints_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureViewpointsIsMutable();
              viewpoints_.addAll(other.viewpoints_);
            }
            onChanged();
          }
        } else {
          if (!other.viewpoints_.isEmpty()) {
            if (viewpointsBuilder_.isEmpty()) {
              viewpointsBuilder_.dispose();
              viewpointsBuilder_ = null;
              viewpoints_ = other.viewpoints_;
              bitField0_ = (bitField0_ & ~0x00000002);
              viewpointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getViewpointsFieldBuilder() : null;
            } else {
              viewpointsBuilder_.addAllMessages(other.viewpoints_);
            }
          }
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.FollowerGroupPB.FollowerGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.FollowerGroupPB.FollowerGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 user_ids = 1;
      private java.util.List<java.lang.Long> userIds_ = java.util.Collections.emptyList();
      private void ensureUserIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userIds_ = new java.util.ArrayList<java.lang.Long>(userIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getUserIdsList() {
        return java.util.Collections.unmodifiableList(userIds_);
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public int getUserIdsCount() {
        return userIds_.size();
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public long getUserIds(int index) {
        return userIds_.get(index);
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public Builder setUserIds(
          int index, long value) {
        ensureUserIdsIsMutable();
        userIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public Builder addUserIds(long value) {
        ensureUserIdsIsMutable();
        userIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public Builder addAllUserIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureUserIdsIsMutable();
        super.addAll(values, userIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 user_ids = 1;</code>
       *
       * <pre>
       * List of user ids in the follower group. Sorted in ascending order.
       * </pre>
       */
      public Builder clearUserIds() {
        userIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated .FollowerGroup.ViewpointInfo viewpoints = 2;
      private java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> viewpoints_ =
        java.util.Collections.emptyList();
      private void ensureViewpointsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          viewpoints_ = new java.util.ArrayList<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo>(viewpoints_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder> viewpointsBuilder_;

      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> getViewpointsList() {
        if (viewpointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(viewpoints_);
        } else {
          return viewpointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public int getViewpointsCount() {
        if (viewpointsBuilder_ == null) {
          return viewpoints_.size();
        } else {
          return viewpointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo getViewpoints(int index) {
        if (viewpointsBuilder_ == null) {
          return viewpoints_.get(index);
        } else {
          return viewpointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder setViewpoints(
          int index, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo value) {
        if (viewpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureViewpointsIsMutable();
          viewpoints_.set(index, value);
          onChanged();
        } else {
          viewpointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder setViewpoints(
          int index, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder builderForValue) {
        if (viewpointsBuilder_ == null) {
          ensureViewpointsIsMutable();
          viewpoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          viewpointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder addViewpoints(co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo value) {
        if (viewpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureViewpointsIsMutable();
          viewpoints_.add(value);
          onChanged();
        } else {
          viewpointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder addViewpoints(
          int index, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo value) {
        if (viewpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureViewpointsIsMutable();
          viewpoints_.add(index, value);
          onChanged();
        } else {
          viewpointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder addViewpoints(
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder builderForValue) {
        if (viewpointsBuilder_ == null) {
          ensureViewpointsIsMutable();
          viewpoints_.add(builderForValue.build());
          onChanged();
        } else {
          viewpointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder addViewpoints(
          int index, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder builderForValue) {
        if (viewpointsBuilder_ == null) {
          ensureViewpointsIsMutable();
          viewpoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          viewpointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder addAllViewpoints(
          java.lang.Iterable<? extends co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo> values) {
        if (viewpointsBuilder_ == null) {
          ensureViewpointsIsMutable();
          super.addAll(values, viewpoints_);
          onChanged();
        } else {
          viewpointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder clearViewpoints() {
        if (viewpointsBuilder_ == null) {
          viewpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          viewpointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public Builder removeViewpoints(int index) {
        if (viewpointsBuilder_ == null) {
          ensureViewpointsIsMutable();
          viewpoints_.remove(index);
          onChanged();
        } else {
          viewpointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder getViewpointsBuilder(
          int index) {
        return getViewpointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder getViewpointsOrBuilder(
          int index) {
        if (viewpointsBuilder_ == null) {
          return viewpoints_.get(index);  } else {
          return viewpointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public java.util.List<? extends co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder> 
           getViewpointsOrBuilderList() {
        if (viewpointsBuilder_ != null) {
          return viewpointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(viewpoints_);
        }
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder addViewpointsBuilder() {
        return getViewpointsFieldBuilder().addBuilder(
            co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder addViewpointsBuilder(
          int index) {
        return getViewpointsFieldBuilder().addBuilder(
            index, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .FollowerGroup.ViewpointInfo viewpoints = 2;</code>
       *
       * <pre>
       * List of viewpoints, sorted by viewpoint id.
       * </pre>
       */
      public java.util.List<co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder> 
           getViewpointsBuilderList() {
        return getViewpointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder> 
          getViewpointsFieldBuilder() {
        if (viewpointsBuilder_ == null) {
          viewpointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfo.Builder, co.viewfinder.proto.FollowerGroupPB.FollowerGroup.ViewpointInfoOrBuilder>(
                  viewpoints_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          viewpoints_ = null;
        }
        return viewpointsBuilder_;
      }

      // optional double weight = 3;
      private double weight_ ;
      /**
       * <code>optional double weight = 3;</code>
       *
       * <pre>
       * Group weight. Computed in-process and not persisted.
       * </pre>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double weight = 3;</code>
       *
       * <pre>
       * Group weight. Computed in-process and not persisted.
       * </pre>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>optional double weight = 3;</code>
       *
       * <pre>
       * Group weight. Computed in-process and not persisted.
       * </pre>
       */
      public Builder setWeight(double value) {
        bitField0_ |= 0x00000004;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double weight = 3;</code>
       *
       * <pre>
       * Group weight. Computed in-process and not persisted.
       * </pre>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FollowerGroup)
    }

    static {
      defaultInstance = new FollowerGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FollowerGroup)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowerGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FollowerGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowerGroup_ViewpointInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FollowerGroup_ViewpointInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FollowerGroup.proto\"\320\001\n\rFollowerGroup\022" +
      "\020\n\010user_ids\030\001 \003(\003\0220\n\nviewpoints\030\002 \003(\0132\034." +
      "FollowerGroup.ViewpointInfo\022\016\n\006weight\030\003 " +
      "\001(\001\032k\n\rViewpointInfo\022\024\n\014viewpoint_id\030\001 \001" +
      "(\003\022\032\n\022earliest_timestamp\030\002 \001(\001\022\030\n\020latest" +
      "_timestamp\030\003 \001(\001\022\016\n\006weight\030\004 \001(\001B&\n\023co.v" +
      "iewfinder.protoB\017FollowerGroupPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FollowerGroup_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FollowerGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FollowerGroup_descriptor,
              new java.lang.String[] { "UserIds", "Viewpoints", "Weight", });
          internal_static_FollowerGroup_ViewpointInfo_descriptor =
            internal_static_FollowerGroup_descriptor.getNestedTypes().get(0);
          internal_static_FollowerGroup_ViewpointInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FollowerGroup_ViewpointInfo_descriptor,
              new java.lang.String[] { "ViewpointId", "EarliestTimestamp", "LatestTimestamp", "Weight", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
