// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FullTextIndexMetadata.proto

package co.viewfinder.proto;

public final class FullTextIndexMetadataPB {
  private FullTextIndexMetadataPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FullTextLexiconMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 token_id = 1;
    /**
     * <code>optional int64 token_id = 1;</code>
     */
    boolean hasTokenId();
    /**
     * <code>optional int64 token_id = 1;</code>
     */
    long getTokenId();

    // optional int64 count = 2;
    /**
     * <code>optional int64 count = 2;</code>
     *
     * <pre>
     * The number of times this token appears in the index.
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int64 count = 2;</code>
     *
     * <pre>
     * The number of times this token appears in the index.
     * </pre>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code FullTextLexiconMetadata}
   */
  public static final class FullTextLexiconMetadata extends
      com.google.protobuf.GeneratedMessage
      implements FullTextLexiconMetadataOrBuilder {
    // Use FullTextLexiconMetadata.newBuilder() to construct.
    private FullTextLexiconMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FullTextLexiconMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FullTextLexiconMetadata defaultInstance;
    public static FullTextLexiconMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public FullTextLexiconMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FullTextLexiconMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tokenId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.FullTextIndexMetadataPB.internal_static_FullTextLexiconMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.FullTextIndexMetadataPB.internal_static_FullTextLexiconMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.class, co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<FullTextLexiconMetadata> PARSER =
        new com.google.protobuf.AbstractParser<FullTextLexiconMetadata>() {
      public FullTextLexiconMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FullTextLexiconMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FullTextLexiconMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 token_id = 1;
    public static final int TOKEN_ID_FIELD_NUMBER = 1;
    private long tokenId_;
    /**
     * <code>optional int64 token_id = 1;</code>
     */
    public boolean hasTokenId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 token_id = 1;</code>
     */
    public long getTokenId() {
      return tokenId_;
    }

    // optional int64 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    /**
     * <code>optional int64 count = 2;</code>
     *
     * <pre>
     * The number of times this token appears in the index.
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 count = 2;</code>
     *
     * <pre>
     * The number of times this token appears in the index.
     * </pre>
     */
    public long getCount() {
      return count_;
    }

    private void initFields() {
      tokenId_ = 0L;
      count_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, tokenId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, tokenId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FullTextLexiconMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.FullTextIndexMetadataPB.internal_static_FullTextLexiconMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.FullTextIndexMetadataPB.internal_static_FullTextLexiconMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.class, co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.Builder.class);
      }

      // Construct using co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tokenId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.FullTextIndexMetadataPB.internal_static_FullTextLexiconMetadata_descriptor;
      }

      public co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata getDefaultInstanceForType() {
        return co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.getDefaultInstance();
      }

      public co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata build() {
        co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata buildPartial() {
        co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata result = new co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tokenId_ = tokenId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata) {
          return mergeFrom((co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata other) {
        if (other == co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata.getDefaultInstance()) return this;
        if (other.hasTokenId()) {
          setTokenId(other.getTokenId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.FullTextIndexMetadataPB.FullTextLexiconMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 token_id = 1;
      private long tokenId_ ;
      /**
       * <code>optional int64 token_id = 1;</code>
       */
      public boolean hasTokenId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 token_id = 1;</code>
       */
      public long getTokenId() {
        return tokenId_;
      }
      /**
       * <code>optional int64 token_id = 1;</code>
       */
      public Builder setTokenId(long value) {
        bitField0_ |= 0x00000001;
        tokenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 token_id = 1;</code>
       */
      public Builder clearTokenId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tokenId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 count = 2;
      private long count_ ;
      /**
       * <code>optional int64 count = 2;</code>
       *
       * <pre>
       * The number of times this token appears in the index.
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 count = 2;</code>
       *
       * <pre>
       * The number of times this token appears in the index.
       * </pre>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>optional int64 count = 2;</code>
       *
       * <pre>
       * The number of times this token appears in the index.
       * </pre>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 count = 2;</code>
       *
       * <pre>
       * The number of times this token appears in the index.
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FullTextLexiconMetadata)
    }

    static {
      defaultInstance = new FullTextLexiconMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FullTextLexiconMetadata)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FullTextLexiconMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FullTextLexiconMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033FullTextIndexMetadata.proto\":\n\027FullTex" +
      "tLexiconMetadata\022\020\n\010token_id\030\001 \001(\003\022\r\n\005co" +
      "unt\030\002 \001(\003B.\n\023co.viewfinder.protoB\027FullTe" +
      "xtIndexMetadataPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FullTextLexiconMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FullTextLexiconMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FullTextLexiconMetadata_descriptor,
              new java.lang.String[] { "TokenId", "Count", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
