// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

package co.viewfinder.proto;

public final class LocationPB {
  private LocationPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double latitude = 1;
    /**
     * <code>optional double latitude = 1;</code>
     *
     * <pre>
     * The latitude/longitude of the breadcrumb.
     * </pre>
     */
    boolean hasLatitude();
    /**
     * <code>optional double latitude = 1;</code>
     *
     * <pre>
     * The latitude/longitude of the breadcrumb.
     * </pre>
     */
    double getLatitude();

    // optional double longitude = 2;
    /**
     * <code>optional double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional double longitude = 2;</code>
     */
    double getLongitude();

    // optional double accuracy = 3;
    /**
     * <code>optional double accuracy = 3;</code>
     *
     * <pre>
     * The accuracy of the location measurement in meters.
     * </pre>
     */
    boolean hasAccuracy();
    /**
     * <code>optional double accuracy = 3;</code>
     *
     * <pre>
     * The accuracy of the location measurement in meters.
     * </pre>
     */
    double getAccuracy();

    // optional double altitude = 4;
    /**
     * <code>optional double altitude = 4;</code>
     */
    boolean hasAltitude();
    /**
     * <code>optional double altitude = 4;</code>
     */
    double getAltitude();
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              accuracy_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              altitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.LocationPB.internal_static_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.LocationPB.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.LocationPB.Location.class, co.viewfinder.proto.LocationPB.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>optional double latitude = 1;</code>
     *
     * <pre>
     * The latitude/longitude of the breadcrumb.
     * </pre>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double latitude = 1;</code>
     *
     * <pre>
     * The latitude/longitude of the breadcrumb.
     * </pre>
     */
    public double getLatitude() {
      return latitude_;
    }

    // optional double longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>optional double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // optional double accuracy = 3;
    public static final int ACCURACY_FIELD_NUMBER = 3;
    private double accuracy_;
    /**
     * <code>optional double accuracy = 3;</code>
     *
     * <pre>
     * The accuracy of the location measurement in meters.
     * </pre>
     */
    public boolean hasAccuracy() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double accuracy = 3;</code>
     *
     * <pre>
     * The accuracy of the location measurement in meters.
     * </pre>
     */
    public double getAccuracy() {
      return accuracy_;
    }

    // optional double altitude = 4;
    public static final int ALTITUDE_FIELD_NUMBER = 4;
    private double altitude_;
    /**
     * <code>optional double altitude = 4;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double altitude = 4;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    private void initFields() {
      latitude_ = 0D;
      longitude_ = 0D;
      accuracy_ = 0D;
      altitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, accuracy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, altitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, accuracy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, altitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.LocationPB.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.LocationPB.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.LocationPB.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.LocationPB.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.LocationPB.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.LocationPB.internal_static_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.LocationPB.internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.LocationPB.Location.class, co.viewfinder.proto.LocationPB.Location.Builder.class);
      }

      // Construct using co.viewfinder.proto.LocationPB.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        accuracy_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        altitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.LocationPB.internal_static_Location_descriptor;
      }

      public co.viewfinder.proto.LocationPB.Location getDefaultInstanceForType() {
        return co.viewfinder.proto.LocationPB.Location.getDefaultInstance();
      }

      public co.viewfinder.proto.LocationPB.Location build() {
        co.viewfinder.proto.LocationPB.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.LocationPB.Location buildPartial() {
        co.viewfinder.proto.LocationPB.Location result = new co.viewfinder.proto.LocationPB.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.accuracy_ = accuracy_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.altitude_ = altitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.LocationPB.Location) {
          return mergeFrom((co.viewfinder.proto.LocationPB.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.LocationPB.Location other) {
        if (other == co.viewfinder.proto.LocationPB.Location.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasAccuracy()) {
          setAccuracy(other.getAccuracy());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.LocationPB.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.LocationPB.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double latitude = 1;
      private double latitude_ ;
      /**
       * <code>optional double latitude = 1;</code>
       *
       * <pre>
       * The latitude/longitude of the breadcrumb.
       * </pre>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double latitude = 1;</code>
       *
       * <pre>
       * The latitude/longitude of the breadcrumb.
       * </pre>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 1;</code>
       *
       * <pre>
       * The latitude/longitude of the breadcrumb.
       * </pre>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 1;</code>
       *
       * <pre>
       * The latitude/longitude of the breadcrumb.
       * </pre>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // optional double longitude = 2;
      private double longitude_ ;
      /**
       * <code>optional double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // optional double accuracy = 3;
      private double accuracy_ ;
      /**
       * <code>optional double accuracy = 3;</code>
       *
       * <pre>
       * The accuracy of the location measurement in meters.
       * </pre>
       */
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double accuracy = 3;</code>
       *
       * <pre>
       * The accuracy of the location measurement in meters.
       * </pre>
       */
      public double getAccuracy() {
        return accuracy_;
      }
      /**
       * <code>optional double accuracy = 3;</code>
       *
       * <pre>
       * The accuracy of the location measurement in meters.
       * </pre>
       */
      public Builder setAccuracy(double value) {
        bitField0_ |= 0x00000004;
        accuracy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double accuracy = 3;</code>
       *
       * <pre>
       * The accuracy of the location measurement in meters.
       * </pre>
       */
      public Builder clearAccuracy() {
        bitField0_ = (bitField0_ & ~0x00000004);
        accuracy_ = 0D;
        onChanged();
        return this;
      }

      // optional double altitude = 4;
      private double altitude_ ;
      /**
       * <code>optional double altitude = 4;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double altitude = 4;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>optional double altitude = 4;</code>
       */
      public Builder setAltitude(double value) {
        bitField0_ |= 0x00000008;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double altitude = 4;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        altitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Location)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Location.proto\"S\n\010Location\022\020\n\010latitude" +
      "\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\020\n\010accuracy\030\003 " +
      "\001(\001\022\020\n\010altitude\030\004 \001(\001B!\n\023co.viewfinder.p" +
      "rotoB\nLocationPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Location_descriptor,
              new java.lang.String[] { "Latitude", "Longitude", "Accuracy", "Altitude", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
