// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Placemark.proto

package co.viewfinder.proto;

public final class PlacemarkPB {
  private PlacemarkPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlacemarkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string iso_country_code = 1;
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    boolean hasIsoCountryCode();
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    java.lang.String getIsoCountryCode();
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getIsoCountryCodeBytes();

    // optional string country = 2;
    /**
     * <code>optional string country = 2;</code>
     */
    boolean hasCountry();
    /**
     * <code>optional string country = 2;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    // optional string state = 3;
    /**
     * <code>optional string state = 3;</code>
     */
    boolean hasState();
    /**
     * <code>optional string state = 3;</code>
     */
    java.lang.String getState();
    /**
     * <code>optional string state = 3;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    // optional string postal_code = 4;
    /**
     * <code>optional string postal_code = 4;</code>
     */
    boolean hasPostalCode();
    /**
     * <code>optional string postal_code = 4;</code>
     */
    java.lang.String getPostalCode();
    /**
     * <code>optional string postal_code = 4;</code>
     */
    com.google.protobuf.ByteString
        getPostalCodeBytes();

    // optional string locality = 5;
    /**
     * <code>optional string locality = 5;</code>
     */
    boolean hasLocality();
    /**
     * <code>optional string locality = 5;</code>
     */
    java.lang.String getLocality();
    /**
     * <code>optional string locality = 5;</code>
     */
    com.google.protobuf.ByteString
        getLocalityBytes();

    // optional string sublocality = 6;
    /**
     * <code>optional string sublocality = 6;</code>
     */
    boolean hasSublocality();
    /**
     * <code>optional string sublocality = 6;</code>
     */
    java.lang.String getSublocality();
    /**
     * <code>optional string sublocality = 6;</code>
     */
    com.google.protobuf.ByteString
        getSublocalityBytes();

    // optional string thoroughfare = 7;
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    boolean hasThoroughfare();
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    java.lang.String getThoroughfare();
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    com.google.protobuf.ByteString
        getThoroughfareBytes();

    // optional string subthoroughfare = 8;
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    boolean hasSubthoroughfare();
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    java.lang.String getSubthoroughfare();
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    com.google.protobuf.ByteString
        getSubthoroughfareBytes();
  }
  /**
   * Protobuf type {@code Placemark}
   */
  public static final class Placemark extends
      com.google.protobuf.GeneratedMessage
      implements PlacemarkOrBuilder {
    // Use Placemark.newBuilder() to construct.
    private Placemark(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Placemark(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Placemark defaultInstance;
    public static Placemark getDefaultInstance() {
      return defaultInstance;
    }

    public Placemark getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Placemark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              isoCountryCode_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              country_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              state_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              postalCode_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              locality_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              sublocality_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              thoroughfare_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              subthoroughfare_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.PlacemarkPB.internal_static_Placemark_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.PlacemarkPB.internal_static_Placemark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.PlacemarkPB.Placemark.class, co.viewfinder.proto.PlacemarkPB.Placemark.Builder.class);
    }

    public static com.google.protobuf.Parser<Placemark> PARSER =
        new com.google.protobuf.AbstractParser<Placemark>() {
      public Placemark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Placemark(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Placemark> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string iso_country_code = 1;
    public static final int ISO_COUNTRY_CODE_FIELD_NUMBER = 1;
    private java.lang.Object isoCountryCode_;
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    public boolean hasIsoCountryCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    public java.lang.String getIsoCountryCode() {
      java.lang.Object ref = isoCountryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          isoCountryCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string iso_country_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIsoCountryCodeBytes() {
      java.lang.Object ref = isoCountryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isoCountryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string country = 2;
    public static final int COUNTRY_FIELD_NUMBER = 2;
    private java.lang.Object country_;
    /**
     * <code>optional string country = 2;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string country = 2;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string state = 3;
    public static final int STATE_FIELD_NUMBER = 3;
    private java.lang.Object state_;
    /**
     * <code>optional string state = 3;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string state = 3;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string state = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string postal_code = 4;
    public static final int POSTAL_CODE_FIELD_NUMBER = 4;
    private java.lang.Object postalCode_;
    /**
     * <code>optional string postal_code = 4;</code>
     */
    public boolean hasPostalCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string postal_code = 4;</code>
     */
    public java.lang.String getPostalCode() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          postalCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string postal_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPostalCodeBytes() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string locality = 5;
    public static final int LOCALITY_FIELD_NUMBER = 5;
    private java.lang.Object locality_;
    /**
     * <code>optional string locality = 5;</code>
     */
    public boolean hasLocality() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string locality = 5;</code>
     */
    public java.lang.String getLocality() {
      java.lang.Object ref = locality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          locality_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string locality = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLocalityBytes() {
      java.lang.Object ref = locality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sublocality = 6;
    public static final int SUBLOCALITY_FIELD_NUMBER = 6;
    private java.lang.Object sublocality_;
    /**
     * <code>optional string sublocality = 6;</code>
     */
    public boolean hasSublocality() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string sublocality = 6;</code>
     */
    public java.lang.String getSublocality() {
      java.lang.Object ref = sublocality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sublocality_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sublocality = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSublocalityBytes() {
      java.lang.Object ref = sublocality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sublocality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string thoroughfare = 7;
    public static final int THOROUGHFARE_FIELD_NUMBER = 7;
    private java.lang.Object thoroughfare_;
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    public boolean hasThoroughfare() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    public java.lang.String getThoroughfare() {
      java.lang.Object ref = thoroughfare_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          thoroughfare_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string thoroughfare = 7;</code>
     */
    public com.google.protobuf.ByteString
        getThoroughfareBytes() {
      java.lang.Object ref = thoroughfare_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thoroughfare_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string subthoroughfare = 8;
    public static final int SUBTHOROUGHFARE_FIELD_NUMBER = 8;
    private java.lang.Object subthoroughfare_;
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    public boolean hasSubthoroughfare() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    public java.lang.String getSubthoroughfare() {
      java.lang.Object ref = subthoroughfare_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subthoroughfare_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subthoroughfare = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSubthoroughfareBytes() {
      java.lang.Object ref = subthoroughfare_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subthoroughfare_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      isoCountryCode_ = "";
      country_ = "";
      state_ = "";
      postalCode_ = "";
      locality_ = "";
      sublocality_ = "";
      thoroughfare_ = "";
      subthoroughfare_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIsoCountryCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCountryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPostalCodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLocalityBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSublocalityBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getThoroughfareBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getSubthoroughfareBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIsoCountryCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCountryBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPostalCodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLocalityBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSublocalityBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getThoroughfareBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSubthoroughfareBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.PlacemarkPB.Placemark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.PlacemarkPB.Placemark prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Placemark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.PlacemarkPB.PlacemarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.PlacemarkPB.internal_static_Placemark_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.PlacemarkPB.internal_static_Placemark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.PlacemarkPB.Placemark.class, co.viewfinder.proto.PlacemarkPB.Placemark.Builder.class);
      }

      // Construct using co.viewfinder.proto.PlacemarkPB.Placemark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isoCountryCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        postalCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        locality_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sublocality_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        thoroughfare_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        subthoroughfare_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.PlacemarkPB.internal_static_Placemark_descriptor;
      }

      public co.viewfinder.proto.PlacemarkPB.Placemark getDefaultInstanceForType() {
        return co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance();
      }

      public co.viewfinder.proto.PlacemarkPB.Placemark build() {
        co.viewfinder.proto.PlacemarkPB.Placemark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.PlacemarkPB.Placemark buildPartial() {
        co.viewfinder.proto.PlacemarkPB.Placemark result = new co.viewfinder.proto.PlacemarkPB.Placemark(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isoCountryCode_ = isoCountryCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.postalCode_ = postalCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.locality_ = locality_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sublocality_ = sublocality_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.thoroughfare_ = thoroughfare_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.subthoroughfare_ = subthoroughfare_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.PlacemarkPB.Placemark) {
          return mergeFrom((co.viewfinder.proto.PlacemarkPB.Placemark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.PlacemarkPB.Placemark other) {
        if (other == co.viewfinder.proto.PlacemarkPB.Placemark.getDefaultInstance()) return this;
        if (other.hasIsoCountryCode()) {
          bitField0_ |= 0x00000001;
          isoCountryCode_ = other.isoCountryCode_;
          onChanged();
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000002;
          country_ = other.country_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000004;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasPostalCode()) {
          bitField0_ |= 0x00000008;
          postalCode_ = other.postalCode_;
          onChanged();
        }
        if (other.hasLocality()) {
          bitField0_ |= 0x00000010;
          locality_ = other.locality_;
          onChanged();
        }
        if (other.hasSublocality()) {
          bitField0_ |= 0x00000020;
          sublocality_ = other.sublocality_;
          onChanged();
        }
        if (other.hasThoroughfare()) {
          bitField0_ |= 0x00000040;
          thoroughfare_ = other.thoroughfare_;
          onChanged();
        }
        if (other.hasSubthoroughfare()) {
          bitField0_ |= 0x00000080;
          subthoroughfare_ = other.subthoroughfare_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.PlacemarkPB.Placemark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.PlacemarkPB.Placemark) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string iso_country_code = 1;
      private java.lang.Object isoCountryCode_ = "";
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public boolean hasIsoCountryCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public java.lang.String getIsoCountryCode() {
        java.lang.Object ref = isoCountryCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          isoCountryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIsoCountryCodeBytes() {
        java.lang.Object ref = isoCountryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isoCountryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public Builder setIsoCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        isoCountryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public Builder clearIsoCountryCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isoCountryCode_ = getDefaultInstance().getIsoCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string iso_country_code = 1;</code>
       */
      public Builder setIsoCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        isoCountryCode_ = value;
        onChanged();
        return this;
      }

      // optional string country = 2;
      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 2;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 2;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        country_ = value;
        onChanged();
        return this;
      }

      // optional string state = 3;
      private java.lang.Object state_ = "";
      /**
       * <code>optional string state = 3;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }

      // optional string postal_code = 4;
      private java.lang.Object postalCode_ = "";
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public boolean hasPostalCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public java.lang.String getPostalCode() {
        java.lang.Object ref = postalCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          postalCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPostalCodeBytes() {
        java.lang.Object ref = postalCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          postalCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public Builder setPostalCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        postalCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public Builder clearPostalCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        postalCode_ = getDefaultInstance().getPostalCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string postal_code = 4;</code>
       */
      public Builder setPostalCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        postalCode_ = value;
        onChanged();
        return this;
      }

      // optional string locality = 5;
      private java.lang.Object locality_ = "";
      /**
       * <code>optional string locality = 5;</code>
       */
      public boolean hasLocality() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string locality = 5;</code>
       */
      public java.lang.String getLocality() {
        java.lang.Object ref = locality_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          locality_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string locality = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLocalityBytes() {
        java.lang.Object ref = locality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string locality = 5;</code>
       */
      public Builder setLocality(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        locality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string locality = 5;</code>
       */
      public Builder clearLocality() {
        bitField0_ = (bitField0_ & ~0x00000010);
        locality_ = getDefaultInstance().getLocality();
        onChanged();
        return this;
      }
      /**
       * <code>optional string locality = 5;</code>
       */
      public Builder setLocalityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        locality_ = value;
        onChanged();
        return this;
      }

      // optional string sublocality = 6;
      private java.lang.Object sublocality_ = "";
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public boolean hasSublocality() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public java.lang.String getSublocality() {
        java.lang.Object ref = sublocality_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sublocality_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSublocalityBytes() {
        java.lang.Object ref = sublocality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sublocality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public Builder setSublocality(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sublocality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public Builder clearSublocality() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sublocality_ = getDefaultInstance().getSublocality();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sublocality = 6;</code>
       */
      public Builder setSublocalityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sublocality_ = value;
        onChanged();
        return this;
      }

      // optional string thoroughfare = 7;
      private java.lang.Object thoroughfare_ = "";
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public boolean hasThoroughfare() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public java.lang.String getThoroughfare() {
        java.lang.Object ref = thoroughfare_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          thoroughfare_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public com.google.protobuf.ByteString
          getThoroughfareBytes() {
        java.lang.Object ref = thoroughfare_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thoroughfare_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public Builder setThoroughfare(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        thoroughfare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public Builder clearThoroughfare() {
        bitField0_ = (bitField0_ & ~0x00000040);
        thoroughfare_ = getDefaultInstance().getThoroughfare();
        onChanged();
        return this;
      }
      /**
       * <code>optional string thoroughfare = 7;</code>
       */
      public Builder setThoroughfareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        thoroughfare_ = value;
        onChanged();
        return this;
      }

      // optional string subthoroughfare = 8;
      private java.lang.Object subthoroughfare_ = "";
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public boolean hasSubthoroughfare() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public java.lang.String getSubthoroughfare() {
        java.lang.Object ref = subthoroughfare_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subthoroughfare_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSubthoroughfareBytes() {
        java.lang.Object ref = subthoroughfare_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subthoroughfare_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public Builder setSubthoroughfare(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        subthoroughfare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public Builder clearSubthoroughfare() {
        bitField0_ = (bitField0_ & ~0x00000080);
        subthoroughfare_ = getDefaultInstance().getSubthoroughfare();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subthoroughfare = 8;</code>
       */
      public Builder setSubthoroughfareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        subthoroughfare_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Placemark)
    }

    static {
      defaultInstance = new Placemark(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Placemark)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Placemark_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Placemark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Placemark.proto\"\260\001\n\tPlacemark\022\030\n\020iso_c" +
      "ountry_code\030\001 \001(\t\022\017\n\007country\030\002 \001(\t\022\r\n\005st" +
      "ate\030\003 \001(\t\022\023\n\013postal_code\030\004 \001(\t\022\020\n\010locali" +
      "ty\030\005 \001(\t\022\023\n\013sublocality\030\006 \001(\t\022\024\n\014thoroug" +
      "hfare\030\007 \001(\t\022\027\n\017subthoroughfare\030\010 \001(\tB\"\n\023" +
      "co.viewfinder.protoB\013PlacemarkPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Placemark_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Placemark_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Placemark_descriptor,
              new java.lang.String[] { "IsoCountryCode", "Country", "State", "PostalCode", "Locality", "Sublocality", "Thoroughfare", "Subthoroughfare", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
