// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscriptionMetadata.proto

package co.viewfinder.proto;

public final class SubscriptionMetadataPB {
  private SubscriptionMetadataPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocalSubscriptionMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string product = 1;
    /**
     * <code>optional string product = 1;</code>
     */
    boolean hasProduct();
    /**
     * <code>optional string product = 1;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>optional string product = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();

    // optional double timestamp = 2;
    /**
     * <code>optional double timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional double timestamp = 2;</code>
     */
    double getTimestamp();

    // optional string receipt = 3;
    /**
     * <code>optional string receipt = 3;</code>
     */
    boolean hasReceipt();
    /**
     * <code>optional string receipt = 3;</code>
     */
    java.lang.String getReceipt();
    /**
     * <code>optional string receipt = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceiptBytes();

    // optional bool recorded = 4;
    /**
     * <code>optional bool recorded = 4;</code>
     */
    boolean hasRecorded();
    /**
     * <code>optional bool recorded = 4;</code>
     */
    boolean getRecorded();
  }
  /**
   * Protobuf type {@code LocalSubscriptionMetadata}
   *
   * <pre>
   * Local subscriptions are mostly-opaque blobs returned by iTunes/StoreKit.
   * They are stored in the DB to recover from crashes between the completion
   * of the itunes transaction and the call to record_subscription.
   *
   * TODO(ben): delete these once they have been recorded and we have seen a
   * corresponding ServerSubscriptionMetadata.
   *
   * TODO(peter): LocalSubscriptionMetadata should be moved into
   * clients/ios/Source. It is iOS specific.
   * </pre>
   */
  public static final class LocalSubscriptionMetadata extends
      com.google.protobuf.GeneratedMessage
      implements LocalSubscriptionMetadataOrBuilder {
    // Use LocalSubscriptionMetadata.newBuilder() to construct.
    private LocalSubscriptionMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LocalSubscriptionMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LocalSubscriptionMetadata defaultInstance;
    public static LocalSubscriptionMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public LocalSubscriptionMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LocalSubscriptionMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              product_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readDouble();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              receipt_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              recorded_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_LocalSubscriptionMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_LocalSubscriptionMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.class, co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<LocalSubscriptionMetadata> PARSER =
        new com.google.protobuf.AbstractParser<LocalSubscriptionMetadata>() {
      public LocalSubscriptionMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocalSubscriptionMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LocalSubscriptionMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string product = 1;
    public static final int PRODUCT_FIELD_NUMBER = 1;
    private java.lang.Object product_;
    /**
     * <code>optional string product = 1;</code>
     */
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string product = 1;</code>
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          product_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string product = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private double timestamp_;
    /**
     * <code>optional double timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double timestamp = 2;</code>
     */
    public double getTimestamp() {
      return timestamp_;
    }

    // optional string receipt = 3;
    public static final int RECEIPT_FIELD_NUMBER = 3;
    private java.lang.Object receipt_;
    /**
     * <code>optional string receipt = 3;</code>
     */
    public boolean hasReceipt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string receipt = 3;</code>
     */
    public java.lang.String getReceipt() {
      java.lang.Object ref = receipt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receipt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string receipt = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceiptBytes() {
      java.lang.Object ref = receipt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receipt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool recorded = 4;
    public static final int RECORDED_FIELD_NUMBER = 4;
    private boolean recorded_;
    /**
     * <code>optional bool recorded = 4;</code>
     */
    public boolean hasRecorded() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool recorded = 4;</code>
     */
    public boolean getRecorded() {
      return recorded_;
    }

    private void initFields() {
      product_ = "";
      timestamp_ = 0D;
      receipt_ = "";
      recorded_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getProductBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReceiptBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, recorded_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProductBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReceiptBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, recorded_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocalSubscriptionMetadata}
     *
     * <pre>
     * Local subscriptions are mostly-opaque blobs returned by iTunes/StoreKit.
     * They are stored in the DB to recover from crashes between the completion
     * of the itunes transaction and the call to record_subscription.
     *
     * TODO(ben): delete these once they have been recorded and we have seen a
     * corresponding ServerSubscriptionMetadata.
     *
     * TODO(peter): LocalSubscriptionMetadata should be moved into
     * clients/ios/Source. It is iOS specific.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_LocalSubscriptionMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_LocalSubscriptionMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.class, co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.Builder.class);
      }

      // Construct using co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        product_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        receipt_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        recorded_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_LocalSubscriptionMetadata_descriptor;
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata getDefaultInstanceForType() {
        return co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.getDefaultInstance();
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata build() {
        co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata buildPartial() {
        co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata result = new co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.product_ = product_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receipt_ = receipt_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.recorded_ = recorded_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata) {
          return mergeFrom((co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata other) {
        if (other == co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata.getDefaultInstance()) return this;
        if (other.hasProduct()) {
          bitField0_ |= 0x00000001;
          product_ = other.product_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasReceipt()) {
          bitField0_ |= 0x00000004;
          receipt_ = other.receipt_;
          onChanged();
        }
        if (other.hasRecorded()) {
          setRecorded(other.getRecorded());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.SubscriptionMetadataPB.LocalSubscriptionMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string product = 1;
      private java.lang.Object product_ = "";
      /**
       * <code>optional string product = 1;</code>
       */
      public boolean hasProduct() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder clearProduct() {
        bitField0_ = (bitField0_ & ~0x00000001);
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        product_ = value;
        onChanged();
        return this;
      }

      // optional double timestamp = 2;
      private double timestamp_ ;
      /**
       * <code>optional double timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double timestamp = 2;</code>
       */
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional double timestamp = 2;</code>
       */
      public Builder setTimestamp(double value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional string receipt = 3;
      private java.lang.Object receipt_ = "";
      /**
       * <code>optional string receipt = 3;</code>
       */
      public boolean hasReceipt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string receipt = 3;</code>
       */
      public java.lang.String getReceipt() {
        java.lang.Object ref = receipt_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receipt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receipt = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceiptBytes() {
        java.lang.Object ref = receipt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receipt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receipt = 3;</code>
       */
      public Builder setReceipt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receipt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receipt = 3;</code>
       */
      public Builder clearReceipt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receipt_ = getDefaultInstance().getReceipt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receipt = 3;</code>
       */
      public Builder setReceiptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receipt_ = value;
        onChanged();
        return this;
      }

      // optional bool recorded = 4;
      private boolean recorded_ ;
      /**
       * <code>optional bool recorded = 4;</code>
       */
      public boolean hasRecorded() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool recorded = 4;</code>
       */
      public boolean getRecorded() {
        return recorded_;
      }
      /**
       * <code>optional bool recorded = 4;</code>
       */
      public Builder setRecorded(boolean value) {
        bitField0_ |= 0x00000008;
        recorded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool recorded = 4;</code>
       */
      public Builder clearRecorded() {
        bitField0_ = (bitField0_ & ~0x00000008);
        recorded_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LocalSubscriptionMetadata)
    }

    static {
      defaultInstance = new LocalSubscriptionMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LocalSubscriptionMetadata)
  }

  public interface ServerSubscriptionMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string transaction_id = 1;
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    boolean hasTransactionId();
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    java.lang.String getTransactionId();
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();

    // optional string subscription_id = 2;
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    boolean hasSubscriptionId();
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    java.lang.String getSubscriptionId();
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubscriptionIdBytes();

    // optional double timestamp = 3;
    /**
     * <code>optional double timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional double timestamp = 3;</code>
     */
    double getTimestamp();

    // optional double expiration_ts = 4;
    /**
     * <code>optional double expiration_ts = 4;</code>
     */
    boolean hasExpirationTs();
    /**
     * <code>optional double expiration_ts = 4;</code>
     */
    double getExpirationTs();

    // optional string product_type = 5;
    /**
     * <code>optional string product_type = 5;</code>
     */
    boolean hasProductType();
    /**
     * <code>optional string product_type = 5;</code>
     */
    java.lang.String getProductType();
    /**
     * <code>optional string product_type = 5;</code>
     */
    com.google.protobuf.ByteString
        getProductTypeBytes();

    // optional double quantity = 6;
    /**
     * <code>optional double quantity = 6;</code>
     */
    boolean hasQuantity();
    /**
     * <code>optional double quantity = 6;</code>
     */
    double getQuantity();

    // optional string payment_type = 7;
    /**
     * <code>optional string payment_type = 7;</code>
     */
    boolean hasPaymentType();
    /**
     * <code>optional string payment_type = 7;</code>
     */
    java.lang.String getPaymentType();
    /**
     * <code>optional string payment_type = 7;</code>
     */
    com.google.protobuf.ByteString
        getPaymentTypeBytes();
  }
  /**
   * Protobuf type {@code ServerSubscriptionMetadata}
   *
   * <pre>
   * The server returns the decoded subscription information via query_users.
   * </pre>
   */
  public static final class ServerSubscriptionMetadata extends
      com.google.protobuf.GeneratedMessage
      implements ServerSubscriptionMetadataOrBuilder {
    // Use ServerSubscriptionMetadata.newBuilder() to construct.
    private ServerSubscriptionMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerSubscriptionMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerSubscriptionMetadata defaultInstance;
    public static ServerSubscriptionMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public ServerSubscriptionMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerSubscriptionMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              transactionId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              subscriptionId_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              expirationTs_ = input.readDouble();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              productType_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              quantity_ = input.readDouble();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              paymentType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_ServerSubscriptionMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_ServerSubscriptionMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.class, co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerSubscriptionMetadata> PARSER =
        new com.google.protobuf.AbstractParser<ServerSubscriptionMetadata>() {
      public ServerSubscriptionMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerSubscriptionMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerSubscriptionMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private java.lang.Object transactionId_;
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    public boolean hasTransactionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transactionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string transaction_id = 1;</code>
     *
     * <pre>
     * Note that the server transaction id will have an "itunes:" prefix not present
     * in the local transaction id (or eventually some other prefix)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string subscription_id = 2;
    public static final int SUBSCRIPTION_ID_FIELD_NUMBER = 2;
    private java.lang.Object subscriptionId_;
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    public boolean hasSubscriptionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    public java.lang.String getSubscriptionId() {
      java.lang.Object ref = subscriptionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subscriptionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subscription_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubscriptionIdBytes() {
      java.lang.Object ref = subscriptionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscriptionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private double timestamp_;
    /**
     * <code>optional double timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double timestamp = 3;</code>
     */
    public double getTimestamp() {
      return timestamp_;
    }

    // optional double expiration_ts = 4;
    public static final int EXPIRATION_TS_FIELD_NUMBER = 4;
    private double expirationTs_;
    /**
     * <code>optional double expiration_ts = 4;</code>
     */
    public boolean hasExpirationTs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double expiration_ts = 4;</code>
     */
    public double getExpirationTs() {
      return expirationTs_;
    }

    // optional string product_type = 5;
    public static final int PRODUCT_TYPE_FIELD_NUMBER = 5;
    private java.lang.Object productType_;
    /**
     * <code>optional string product_type = 5;</code>
     */
    public boolean hasProductType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string product_type = 5;</code>
     */
    public java.lang.String getProductType() {
      java.lang.Object ref = productType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string product_type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductTypeBytes() {
      java.lang.Object ref = productType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double quantity = 6;
    public static final int QUANTITY_FIELD_NUMBER = 6;
    private double quantity_;
    /**
     * <code>optional double quantity = 6;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double quantity = 6;</code>
     */
    public double getQuantity() {
      return quantity_;
    }

    // optional string payment_type = 7;
    public static final int PAYMENT_TYPE_FIELD_NUMBER = 7;
    private java.lang.Object paymentType_;
    /**
     * <code>optional string payment_type = 7;</code>
     */
    public boolean hasPaymentType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string payment_type = 7;</code>
     */
    public java.lang.String getPaymentType() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paymentType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payment_type = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentTypeBytes() {
      java.lang.Object ref = paymentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      transactionId_ = "";
      subscriptionId_ = "";
      timestamp_ = 0D;
      expirationTs_ = 0D;
      productType_ = "";
      quantity_ = 0D;
      paymentType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTransactionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSubscriptionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, expirationTs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getProductTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, quantity_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPaymentTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTransactionIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSubscriptionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, expirationTs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getProductTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, quantity_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPaymentTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerSubscriptionMetadata}
     *
     * <pre>
     * The server returns the decoded subscription information via query_users.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_ServerSubscriptionMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_ServerSubscriptionMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.class, co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.Builder.class);
      }

      // Construct using co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transactionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        subscriptionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        expirationTs_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        productType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        quantity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        paymentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.viewfinder.proto.SubscriptionMetadataPB.internal_static_ServerSubscriptionMetadata_descriptor;
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata getDefaultInstanceForType() {
        return co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.getDefaultInstance();
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata build() {
        co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata buildPartial() {
        co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata result = new co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transactionId_ = transactionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.subscriptionId_ = subscriptionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.expirationTs_ = expirationTs_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.productType_ = productType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.paymentType_ = paymentType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata) {
          return mergeFrom((co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata other) {
        if (other == co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          bitField0_ |= 0x00000001;
          transactionId_ = other.transactionId_;
          onChanged();
        }
        if (other.hasSubscriptionId()) {
          bitField0_ |= 0x00000002;
          subscriptionId_ = other.subscriptionId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasExpirationTs()) {
          setExpirationTs(other.getExpirationTs());
        }
        if (other.hasProductType()) {
          bitField0_ |= 0x00000010;
          productType_ = other.productType_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPaymentType()) {
          bitField0_ |= 0x00000040;
          paymentType_ = other.paymentType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.viewfinder.proto.SubscriptionMetadataPB.ServerSubscriptionMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string transaction_id = 1;
      private java.lang.Object transactionId_ = "";
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public boolean hasTransactionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public Builder clearTransactionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transactionId_ = getDefaultInstance().getTransactionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transaction_id = 1;</code>
       *
       * <pre>
       * Note that the server transaction id will have an "itunes:" prefix not present
       * in the local transaction id (or eventually some other prefix)
       * </pre>
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transactionId_ = value;
        onChanged();
        return this;
      }

      // optional string subscription_id = 2;
      private java.lang.Object subscriptionId_ = "";
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public boolean hasSubscriptionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public java.lang.String getSubscriptionId() {
        java.lang.Object ref = subscriptionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subscriptionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubscriptionIdBytes() {
        java.lang.Object ref = subscriptionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscriptionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public Builder setSubscriptionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subscriptionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public Builder clearSubscriptionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        subscriptionId_ = getDefaultInstance().getSubscriptionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subscription_id = 2;</code>
       */
      public Builder setSubscriptionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subscriptionId_ = value;
        onChanged();
        return this;
      }

      // optional double timestamp = 3;
      private double timestamp_ ;
      /**
       * <code>optional double timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double timestamp = 3;</code>
       */
      public double getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional double timestamp = 3;</code>
       */
      public Builder setTimestamp(double value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0D;
        onChanged();
        return this;
      }

      // optional double expiration_ts = 4;
      private double expirationTs_ ;
      /**
       * <code>optional double expiration_ts = 4;</code>
       */
      public boolean hasExpirationTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double expiration_ts = 4;</code>
       */
      public double getExpirationTs() {
        return expirationTs_;
      }
      /**
       * <code>optional double expiration_ts = 4;</code>
       */
      public Builder setExpirationTs(double value) {
        bitField0_ |= 0x00000008;
        expirationTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double expiration_ts = 4;</code>
       */
      public Builder clearExpirationTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        expirationTs_ = 0D;
        onChanged();
        return this;
      }

      // optional string product_type = 5;
      private java.lang.Object productType_ = "";
      /**
       * <code>optional string product_type = 5;</code>
       */
      public boolean hasProductType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string product_type = 5;</code>
       */
      public java.lang.String getProductType() {
        java.lang.Object ref = productType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          productType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product_type = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProductTypeBytes() {
        java.lang.Object ref = productType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product_type = 5;</code>
       */
      public Builder setProductType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        productType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_type = 5;</code>
       */
      public Builder clearProductType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        productType_ = getDefaultInstance().getProductType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_type = 5;</code>
       */
      public Builder setProductTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        productType_ = value;
        onChanged();
        return this;
      }

      // optional double quantity = 6;
      private double quantity_ ;
      /**
       * <code>optional double quantity = 6;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double quantity = 6;</code>
       */
      public double getQuantity() {
        return quantity_;
      }
      /**
       * <code>optional double quantity = 6;</code>
       */
      public Builder setQuantity(double value) {
        bitField0_ |= 0x00000020;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double quantity = 6;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        quantity_ = 0D;
        onChanged();
        return this;
      }

      // optional string payment_type = 7;
      private java.lang.Object paymentType_ = "";
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public boolean hasPaymentType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public java.lang.String getPaymentType() {
        java.lang.Object ref = paymentType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          paymentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPaymentTypeBytes() {
        java.lang.Object ref = paymentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public Builder setPaymentType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        paymentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public Builder clearPaymentType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        paymentType_ = getDefaultInstance().getPaymentType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payment_type = 7;</code>
       */
      public Builder setPaymentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        paymentType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerSubscriptionMetadata)
    }

    static {
      defaultInstance = new ServerSubscriptionMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerSubscriptionMetadata)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalSubscriptionMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalSubscriptionMetadata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerSubscriptionMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerSubscriptionMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SubscriptionMetadata.proto\"b\n\031LocalSub" +
      "scriptionMetadata\022\017\n\007product\030\001 \001(\t\022\021\n\tti" +
      "mestamp\030\002 \001(\001\022\017\n\007receipt\030\003 \001(\t\022\020\n\010record" +
      "ed\030\004 \001(\010\"\265\001\n\032ServerSubscriptionMetadata\022" +
      "\026\n\016transaction_id\030\001 \001(\t\022\027\n\017subscription_" +
      "id\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\001\022\025\n\rexpiratio" +
      "n_ts\030\004 \001(\001\022\024\n\014product_type\030\005 \001(\t\022\020\n\010quan" +
      "tity\030\006 \001(\001\022\024\n\014payment_type\030\007 \001(\tB-\n\023co.v" +
      "iewfinder.protoB\026SubscriptionMetadataPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LocalSubscriptionMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LocalSubscriptionMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LocalSubscriptionMetadata_descriptor,
              new java.lang.String[] { "Product", "Timestamp", "Receipt", "Recorded", });
          internal_static_ServerSubscriptionMetadata_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ServerSubscriptionMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerSubscriptionMetadata_descriptor,
              new java.lang.String[] { "TransactionId", "SubscriptionId", "Timestamp", "ExpirationTs", "ProductType", "Quantity", "PaymentType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
